#include "material.h"

const mat_biome_t mat_biome_badlands_d = {
	.name = "minecraft:badlands",
	.name_length = 18,
	.precipitation = mat_precipitation_none,
	.depth = 0.1,
	.temperature = 2.0,
	.scale = 0.2,
	.downfall = 0.0,
	.category = mat_biome_category_mesa,
	.effects = {
		.sky_color = 7254527,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.has_foliage_color = true,
		.foliage_color = 10387789,
		.has_grass_color = true,
		.grass_color = 9470285,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_badlands_plateau_d = {
	.name = "minecraft:badlands_plateau",
	.name_length = 26,
	.precipitation = mat_precipitation_none,
	.depth = 1.5,
	.temperature = 2.0,
	.scale = 0.025,
	.downfall = 0.0,
	.category = mat_biome_category_mesa,
	.effects = {
		.sky_color = 7254527,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.has_foliage_color = true,
		.foliage_color = 10387789,
		.has_grass_color = true,
		.grass_color = 9470285,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_bamboo_jungle_d = {
	.name = "minecraft:bamboo_jungle",
	.name_length = 23,
	.precipitation = mat_precipitation_rain,
	.depth = 0.1,
	.temperature = 0.95,
	.scale = 0.2,
	.downfall = 0.9,
	.category = mat_biome_category_jungle,
	.effects = {
		.sky_color = 7842047,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_bamboo_jungle_hills_d = {
	.name = "minecraft:bamboo_jungle_hills",
	.name_length = 29,
	.precipitation = mat_precipitation_rain,
	.depth = 0.45,
	.temperature = 0.95,
	.scale = 0.3,
	.downfall = 0.9,
	.category = mat_biome_category_jungle,
	.effects = {
		.sky_color = 7842047,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_basalt_deltas_d = {
	.name = "minecraft:basalt_deltas",
	.name_length = 23,
	.precipitation = mat_precipitation_none,
	.depth = 0.1,
	.temperature = 2.0,
	.scale = 0.2,
	.downfall = 0.0,
	.category = mat_biome_category_nether,
	.effects = {
		.sky_color = 7254527,
		.water_fog_color = 4341314,
		.fog_color = 6840176,
		.music = {
			.sound = "minecraft:music.nether.basalt_deltas",
			.sound_length = 36,
			.max_delay = 24000,
			.min_delay = 12000,
		},
		.ambient_sound = "minecraft:ambient.basalt_deltas.loop",
		.ambient_sound_length = 36,
		.additions_sound = {
			.sound = "minecraft:ambient.basalt_deltas.additions",
			.sound_length = 41,
			.tick_chance = 0.0111,
		},
		.mood_sound = {
			.sound = "minecraft:ambient.basalt_deltas.mood",
			.sound_length = 36,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
	.particle = {
		.probability = 0.118093334,
		.options = {
			.type = "minecraft:white_ash",
			.type_length = 19,
		},
	},
};
const mat_biome_t mat_biome_beach_d = {
	.name = "minecraft:beach",
	.name_length = 15,
	.precipitation = mat_precipitation_rain,
	.depth = 0.0,
	.temperature = 0.8,
	.scale = 0.025,
	.downfall = 0.4,
	.category = mat_biome_category_beach,
	.effects = {
		.sky_color = 7907327,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_birch_forest_d = {
	.name = "minecraft:birch_forest",
	.name_length = 22,
	.precipitation = mat_precipitation_rain,
	.depth = 0.1,
	.temperature = 0.6,
	.scale = 0.2,
	.downfall = 0.6,
	.category = mat_biome_category_forest,
	.effects = {
		.sky_color = 8037887,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_birch_forest_hills_d = {
	.name = "minecraft:birch_forest_hills",
	.name_length = 28,
	.precipitation = mat_precipitation_rain,
	.depth = 0.45,
	.temperature = 0.6,
	.scale = 0.3,
	.downfall = 0.6,
	.category = mat_biome_category_forest,
	.effects = {
		.sky_color = 8037887,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_cold_ocean_d = {
	.name = "minecraft:cold_ocean",
	.name_length = 20,
	.precipitation = mat_precipitation_rain,
	.depth = -1.0,
	.temperature = 0.5,
	.scale = 0.1,
	.downfall = 0.5,
	.category = mat_biome_category_ocean,
	.effects = {
		.sky_color = 8103167,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_crimson_forest_d = {
	.name = "minecraft:crimson_forest",
	.name_length = 24,
	.precipitation = mat_precipitation_none,
	.depth = 0.1,
	.temperature = 2.0,
	.scale = 0.2,
	.downfall = 0.0,
	.category = mat_biome_category_nether,
	.effects = {
		.sky_color = 7254527,
		.water_fog_color = 329011,
		.fog_color = 3343107,
		.music = {
			.sound = "minecraft:music.nether.crimson_forest",
			.sound_length = 37,
			.max_delay = 24000,
			.min_delay = 12000,
		},
		.ambient_sound = "minecraft:ambient.crimson_forest.loop",
		.ambient_sound_length = 37,
		.additions_sound = {
			.sound = "minecraft:ambient.crimson_forest.additions",
			.sound_length = 42,
			.tick_chance = 0.0111,
		},
		.mood_sound = {
			.sound = "minecraft:ambient.crimson_forest.mood",
			.sound_length = 37,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
	.particle = {
		.probability = 0.025,
		.options = {
			.type = "minecraft:crimson_spore",
			.type_length = 23,
		},
	},
};
const mat_biome_t mat_biome_dark_forest_d = {
	.name = "minecraft:dark_forest",
	.name_length = 21,
	.precipitation = mat_precipitation_rain,
	.depth = 0.1,
	.temperature = 0.7,
	.scale = 0.2,
	.downfall = 0.8,
	.category = mat_biome_category_forest,
	.effects = {
		.sky_color = 7972607,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.grass_color_modifier = mat_grass_color_modifier_dark_forest,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_dark_forest_hills_d = {
	.name = "minecraft:dark_forest_hills",
	.name_length = 27,
	.precipitation = mat_precipitation_rain,
	.depth = 0.2,
	.temperature = 0.7,
	.scale = 0.4,
	.downfall = 0.8,
	.category = mat_biome_category_forest,
	.effects = {
		.sky_color = 7972607,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.grass_color_modifier = mat_grass_color_modifier_dark_forest,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_deep_cold_ocean_d = {
	.name = "minecraft:deep_cold_ocean",
	.name_length = 25,
	.precipitation = mat_precipitation_rain,
	.depth = -1.8,
	.temperature = 0.5,
	.scale = 0.1,
	.downfall = 0.5,
	.category = mat_biome_category_ocean,
	.effects = {
		.sky_color = 8103167,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_deep_frozen_ocean_d = {
	.name = "minecraft:deep_frozen_ocean",
	.name_length = 27,
	.precipitation = mat_precipitation_rain,
	.depth = -1.8,
	.temperature = 0.5,
	.temperature_modifier = mat_temperature_modifier_frozen,
	.scale = 0.1,
	.downfall = 0.5,
	.category = mat_biome_category_ocean,
	.effects = {
		.sky_color = 8103167,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_deep_lukewarm_ocean_d = {
	.name = "minecraft:deep_lukewarm_ocean",
	.name_length = 29,
	.precipitation = mat_precipitation_rain,
	.depth = -1.8,
	.temperature = 0.5,
	.scale = 0.1,
	.downfall = 0.5,
	.category = mat_biome_category_ocean,
	.effects = {
		.sky_color = 8103167,
		.water_fog_color = 267827,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_deep_ocean_d = {
	.name = "minecraft:deep_ocean",
	.name_length = 20,
	.precipitation = mat_precipitation_rain,
	.depth = -1.8,
	.temperature = 0.5,
	.scale = 0.1,
	.downfall = 0.5,
	.category = mat_biome_category_ocean,
	.effects = {
		.sky_color = 8103167,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_deep_warm_ocean_d = {
	.name = "minecraft:deep_warm_ocean",
	.name_length = 25,
	.precipitation = mat_precipitation_rain,
	.depth = -1.8,
	.temperature = 0.5,
	.scale = 0.1,
	.downfall = 0.5,
	.category = mat_biome_category_ocean,
	.effects = {
		.sky_color = 8103167,
		.water_fog_color = 270131,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_desert_d = {
	.name = "minecraft:desert",
	.name_length = 16,
	.precipitation = mat_precipitation_none,
	.depth = 0.125,
	.temperature = 2.0,
	.scale = 0.05,
	.downfall = 0.0,
	.category = mat_biome_category_desert,
	.effects = {
		.sky_color = 7254527,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_desert_hills_d = {
	.name = "minecraft:desert_hills",
	.name_length = 22,
	.precipitation = mat_precipitation_none,
	.depth = 0.45,
	.temperature = 2.0,
	.scale = 0.3,
	.downfall = 0.0,
	.category = mat_biome_category_desert,
	.effects = {
		.sky_color = 7254527,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_desert_lakes_d = {
	.name = "minecraft:desert_lakes",
	.name_length = 22,
	.precipitation = mat_precipitation_none,
	.depth = 0.225,
	.temperature = 2.0,
	.scale = 0.25,
	.downfall = 0.0,
	.category = mat_biome_category_desert,
	.effects = {
		.sky_color = 7254527,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_dripstone_caves_d = {
	.name = "minecraft:dripstone_caves",
	.name_length = 25,
	.precipitation = mat_precipitation_rain,
	.depth = 0.125,
	.temperature = 0.8,
	.scale = 0.05,
	.downfall = 0.4,
	.category = mat_biome_category_underground,
	.effects = {
		.sky_color = 7907327,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_end_barrens_d = {
	.name = "minecraft:end_barrens",
	.name_length = 21,
	.precipitation = mat_precipitation_none,
	.depth = 0.1,
	.temperature = 0.5,
	.scale = 0.2,
	.downfall = 0.5,
	.category = mat_biome_category_the_end,
	.effects = {
		.sky_color = 0,
		.water_fog_color = 329011,
		.fog_color = 10518688,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_end_highlands_d = {
	.name = "minecraft:end_highlands",
	.name_length = 23,
	.precipitation = mat_precipitation_none,
	.depth = 0.1,
	.temperature = 0.5,
	.scale = 0.2,
	.downfall = 0.5,
	.category = mat_biome_category_the_end,
	.effects = {
		.sky_color = 0,
		.water_fog_color = 329011,
		.fog_color = 10518688,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_end_midlands_d = {
	.name = "minecraft:end_midlands",
	.name_length = 22,
	.precipitation = mat_precipitation_none,
	.depth = 0.1,
	.temperature = 0.5,
	.scale = 0.2,
	.downfall = 0.5,
	.category = mat_biome_category_the_end,
	.effects = {
		.sky_color = 0,
		.water_fog_color = 329011,
		.fog_color = 10518688,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_eroded_badlands_d = {
	.name = "minecraft:eroded_badlands",
	.name_length = 25,
	.precipitation = mat_precipitation_none,
	.depth = 0.1,
	.temperature = 2.0,
	.scale = 0.2,
	.downfall = 0.0,
	.category = mat_biome_category_mesa,
	.effects = {
		.sky_color = 7254527,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.has_foliage_color = true,
		.foliage_color = 10387789,
		.has_grass_color = true,
		.grass_color = 9470285,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_flower_forest_d = {
	.name = "minecraft:flower_forest",
	.name_length = 23,
	.precipitation = mat_precipitation_rain,
	.depth = 0.1,
	.temperature = 0.7,
	.scale = 0.4,
	.downfall = 0.8,
	.category = mat_biome_category_forest,
	.effects = {
		.sky_color = 7972607,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_forest_d = {
	.name = "minecraft:forest",
	.name_length = 16,
	.precipitation = mat_precipitation_rain,
	.depth = 0.1,
	.temperature = 0.7,
	.scale = 0.2,
	.downfall = 0.8,
	.category = mat_biome_category_forest,
	.effects = {
		.sky_color = 7972607,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_frozen_ocean_d = {
	.name = "minecraft:frozen_ocean",
	.name_length = 22,
	.precipitation = mat_precipitation_snow,
	.depth = -1.0,
	.temperature = 0.0,
	.temperature_modifier = mat_temperature_modifier_frozen,
	.scale = 0.1,
	.downfall = 0.5,
	.category = mat_biome_category_ocean,
	.effects = {
		.sky_color = 8364543,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_frozen_river_d = {
	.name = "minecraft:frozen_river",
	.name_length = 22,
	.precipitation = mat_precipitation_snow,
	.depth = -0.5,
	.temperature = 0.0,
	.scale = 0.0,
	.downfall = 0.5,
	.category = mat_biome_category_river,
	.effects = {
		.sky_color = 8364543,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_giant_spruce_taiga_d = {
	.name = "minecraft:giant_spruce_taiga",
	.name_length = 28,
	.precipitation = mat_precipitation_rain,
	.depth = 0.2,
	.temperature = 0.25,
	.scale = 0.2,
	.downfall = 0.8,
	.category = mat_biome_category_taiga,
	.effects = {
		.sky_color = 8233983,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_giant_spruce_taiga_hills_d = {
	.name = "minecraft:giant_spruce_taiga_hills",
	.name_length = 34,
	.precipitation = mat_precipitation_rain,
	.depth = 0.2,
	.temperature = 0.25,
	.scale = 0.2,
	.downfall = 0.8,
	.category = mat_biome_category_taiga,
	.effects = {
		.sky_color = 8233983,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_giant_tree_taiga_d = {
	.name = "minecraft:giant_tree_taiga",
	.name_length = 26,
	.precipitation = mat_precipitation_rain,
	.depth = 0.2,
	.temperature = 0.3,
	.scale = 0.2,
	.downfall = 0.8,
	.category = mat_biome_category_taiga,
	.effects = {
		.sky_color = 8168447,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_giant_tree_taiga_hills_d = {
	.name = "minecraft:giant_tree_taiga_hills",
	.name_length = 32,
	.precipitation = mat_precipitation_rain,
	.depth = 0.45,
	.temperature = 0.3,
	.scale = 0.3,
	.downfall = 0.8,
	.category = mat_biome_category_taiga,
	.effects = {
		.sky_color = 8168447,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_gravelly_mountains_d = {
	.name = "minecraft:gravelly_mountains",
	.name_length = 28,
	.precipitation = mat_precipitation_rain,
	.depth = 1.0,
	.temperature = 0.2,
	.scale = 0.5,
	.downfall = 0.3,
	.category = mat_biome_category_extreme_hills,
	.effects = {
		.sky_color = 8233727,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_ice_spikes_d = {
	.name = "minecraft:ice_spikes",
	.name_length = 20,
	.precipitation = mat_precipitation_snow,
	.depth = 0.425,
	.temperature = 0.0,
	.scale = 0.45000002,
	.downfall = 0.5,
	.category = mat_biome_category_icy,
	.effects = {
		.sky_color = 8364543,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_jungle_d = {
	.name = "minecraft:jungle",
	.name_length = 16,
	.precipitation = mat_precipitation_rain,
	.depth = 0.1,
	.temperature = 0.95,
	.scale = 0.2,
	.downfall = 0.9,
	.category = mat_biome_category_jungle,
	.effects = {
		.sky_color = 7842047,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_jungle_edge_d = {
	.name = "minecraft:jungle_edge",
	.name_length = 21,
	.precipitation = mat_precipitation_rain,
	.depth = 0.1,
	.temperature = 0.95,
	.scale = 0.2,
	.downfall = 0.8,
	.category = mat_biome_category_jungle,
	.effects = {
		.sky_color = 7842047,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_jungle_hills_d = {
	.name = "minecraft:jungle_hills",
	.name_length = 22,
	.precipitation = mat_precipitation_rain,
	.depth = 0.45,
	.temperature = 0.95,
	.scale = 0.3,
	.downfall = 0.9,
	.category = mat_biome_category_jungle,
	.effects = {
		.sky_color = 7842047,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_lukewarm_ocean_d = {
	.name = "minecraft:lukewarm_ocean",
	.name_length = 24,
	.precipitation = mat_precipitation_rain,
	.depth = -1.0,
	.temperature = 0.5,
	.scale = 0.1,
	.downfall = 0.5,
	.category = mat_biome_category_ocean,
	.effects = {
		.sky_color = 8103167,
		.water_fog_color = 267827,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_lush_caves_d = {
	.name = "minecraft:lush_caves",
	.name_length = 20,
	.precipitation = mat_precipitation_rain,
	.depth = 0.1,
	.temperature = 0.5,
	.scale = 0.2,
	.downfall = 0.5,
	.category = mat_biome_category_underground,
	.effects = {
		.sky_color = 8103167,
		.water_fog_color = 329011,
		.fog_color = 12638463,
	},
};
const mat_biome_t mat_biome_modified_badlands_plateau_d = {
	.name = "minecraft:modified_badlands_plateau",
	.name_length = 35,
	.precipitation = mat_precipitation_none,
	.depth = 0.45,
	.temperature = 2.0,
	.scale = 0.3,
	.downfall = 0.0,
	.category = mat_biome_category_mesa,
	.effects = {
		.sky_color = 7254527,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.has_foliage_color = true,
		.foliage_color = 10387789,
		.has_grass_color = true,
		.grass_color = 9470285,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_modified_gravelly_mountains_d = {
	.name = "minecraft:modified_gravelly_mountains",
	.name_length = 37,
	.precipitation = mat_precipitation_rain,
	.depth = 1.0,
	.temperature = 0.2,
	.scale = 0.5,
	.downfall = 0.3,
	.category = mat_biome_category_extreme_hills,
	.effects = {
		.sky_color = 8233727,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_modified_jungle_d = {
	.name = "minecraft:modified_jungle",
	.name_length = 25,
	.precipitation = mat_precipitation_rain,
	.depth = 0.2,
	.temperature = 0.95,
	.scale = 0.4,
	.downfall = 0.9,
	.category = mat_biome_category_jungle,
	.effects = {
		.sky_color = 7842047,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_modified_jungle_edge_d = {
	.name = "minecraft:modified_jungle_edge",
	.name_length = 30,
	.precipitation = mat_precipitation_rain,
	.depth = 0.2,
	.temperature = 0.95,
	.scale = 0.4,
	.downfall = 0.8,
	.category = mat_biome_category_jungle,
	.effects = {
		.sky_color = 7842047,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_modified_wooded_badlands_plateau_d = {
	.name = "minecraft:modified_wooded_badlands_plateau",
	.name_length = 42,
	.precipitation = mat_precipitation_none,
	.depth = 0.45,
	.temperature = 2.0,
	.scale = 0.3,
	.downfall = 0.0,
	.category = mat_biome_category_mesa,
	.effects = {
		.sky_color = 7254527,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.has_foliage_color = true,
		.foliage_color = 10387789,
		.has_grass_color = true,
		.grass_color = 9470285,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_mountains_d = {
	.name = "minecraft:mountains",
	.name_length = 19,
	.precipitation = mat_precipitation_rain,
	.depth = 1.0,
	.temperature = 0.2,
	.scale = 0.5,
	.downfall = 0.3,
	.category = mat_biome_category_extreme_hills,
	.effects = {
		.sky_color = 8233727,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_mountain_edge_d = {
	.name = "minecraft:mountain_edge",
	.name_length = 23,
	.precipitation = mat_precipitation_rain,
	.depth = 0.8,
	.temperature = 0.2,
	.scale = 0.3,
	.downfall = 0.3,
	.category = mat_biome_category_extreme_hills,
	.effects = {
		.sky_color = 8233727,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_mushroom_fields_d = {
	.name = "minecraft:mushroom_fields",
	.name_length = 25,
	.precipitation = mat_precipitation_rain,
	.depth = 0.2,
	.temperature = 0.9,
	.scale = 0.3,
	.downfall = 1.0,
	.category = mat_biome_category_mushroom,
	.effects = {
		.sky_color = 7842047,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_mushroom_field_shore_d = {
	.name = "minecraft:mushroom_field_shore",
	.name_length = 30,
	.precipitation = mat_precipitation_rain,
	.depth = 0.0,
	.temperature = 0.9,
	.scale = 0.025,
	.downfall = 1.0,
	.category = mat_biome_category_mushroom,
	.effects = {
		.sky_color = 7842047,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_nether_wastes_d = {
	.name = "minecraft:nether_wastes",
	.name_length = 23,
	.precipitation = mat_precipitation_none,
	.depth = 0.1,
	.temperature = 2.0,
	.scale = 0.2,
	.downfall = 0.0,
	.category = mat_biome_category_nether,
	.effects = {
		.sky_color = 7254527,
		.water_fog_color = 329011,
		.fog_color = 3344392,
		.music = {
			.sound = "minecraft:music.nether.nether_wastes",
			.sound_length = 36,
			.max_delay = 24000,
			.min_delay = 12000,
		},
		.ambient_sound = "minecraft:ambient.nether_wastes.loop",
		.ambient_sound_length = 36,
		.additions_sound = {
			.sound = "minecraft:ambient.nether_wastes.additions",
			.sound_length = 41,
			.tick_chance = 0.0111,
		},
		.mood_sound = {
			.sound = "minecraft:ambient.nether_wastes.mood",
			.sound_length = 36,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_ocean_d = {
	.name = "minecraft:ocean",
	.name_length = 15,
	.precipitation = mat_precipitation_rain,
	.depth = -1.0,
	.temperature = 0.5,
	.scale = 0.1,
	.downfall = 0.5,
	.category = mat_biome_category_ocean,
	.effects = {
		.sky_color = 8103167,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_plains_d = {
	.name = "minecraft:plains",
	.name_length = 16,
	.precipitation = mat_precipitation_rain,
	.depth = 0.125,
	.temperature = 0.8,
	.scale = 0.05,
	.downfall = 0.4,
	.category = mat_biome_category_plains,
	.effects = {
		.sky_color = 7907327,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_river_d = {
	.name = "minecraft:river",
	.name_length = 15,
	.precipitation = mat_precipitation_rain,
	.depth = -0.5,
	.temperature = 0.5,
	.scale = 0.0,
	.downfall = 0.5,
	.category = mat_biome_category_river,
	.effects = {
		.sky_color = 8103167,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_savanna_d = {
	.name = "minecraft:savanna",
	.name_length = 17,
	.precipitation = mat_precipitation_none,
	.depth = 0.125,
	.temperature = 1.2,
	.scale = 0.05,
	.downfall = 0.0,
	.category = mat_biome_category_savanna,
	.effects = {
		.sky_color = 7711487,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_savanna_plateau_d = {
	.name = "minecraft:savanna_plateau",
	.name_length = 25,
	.precipitation = mat_precipitation_none,
	.depth = 1.5,
	.temperature = 1.0,
	.scale = 0.025,
	.downfall = 0.0,
	.category = mat_biome_category_savanna,
	.effects = {
		.sky_color = 7776511,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_shattered_savanna_d = {
	.name = "minecraft:shattered_savanna",
	.name_length = 27,
	.precipitation = mat_precipitation_none,
	.depth = 0.3625,
	.temperature = 1.1,
	.scale = 1.225,
	.downfall = 0.0,
	.category = mat_biome_category_savanna,
	.effects = {
		.sky_color = 7776767,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_shattered_savanna_plateau_d = {
	.name = "minecraft:shattered_savanna_plateau",
	.name_length = 35,
	.precipitation = mat_precipitation_none,
	.depth = 1.05,
	.temperature = 1.0,
	.scale = 1.2125001,
	.downfall = 0.0,
	.category = mat_biome_category_savanna,
	.effects = {
		.sky_color = 7776511,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_small_end_islands_d = {
	.name = "minecraft:small_end_islands",
	.name_length = 27,
	.precipitation = mat_precipitation_none,
	.depth = 0.1,
	.temperature = 0.5,
	.scale = 0.2,
	.downfall = 0.5,
	.category = mat_biome_category_the_end,
	.effects = {
		.sky_color = 0,
		.water_fog_color = 329011,
		.fog_color = 10518688,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_snowy_beach_d = {
	.name = "minecraft:snowy_beach",
	.name_length = 21,
	.precipitation = mat_precipitation_snow,
	.depth = 0.0,
	.temperature = 0.05,
	.scale = 0.025,
	.downfall = 0.3,
	.category = mat_biome_category_beach,
	.effects = {
		.sky_color = 8364543,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_snowy_mountains_d = {
	.name = "minecraft:snowy_mountains",
	.name_length = 25,
	.precipitation = mat_precipitation_snow,
	.depth = 0.45,
	.temperature = 0.0,
	.scale = 0.3,
	.downfall = 0.5,
	.category = mat_biome_category_icy,
	.effects = {
		.sky_color = 8364543,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_snowy_taiga_d = {
	.name = "minecraft:snowy_taiga",
	.name_length = 21,
	.precipitation = mat_precipitation_snow,
	.depth = 0.2,
	.temperature = -0.5,
	.scale = 0.2,
	.downfall = 0.4,
	.category = mat_biome_category_taiga,
	.effects = {
		.sky_color = 8625919,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_snowy_taiga_hills_d = {
	.name = "minecraft:snowy_taiga_hills",
	.name_length = 27,
	.precipitation = mat_precipitation_snow,
	.depth = 0.45,
	.temperature = -0.5,
	.scale = 0.3,
	.downfall = 0.4,
	.category = mat_biome_category_taiga,
	.effects = {
		.sky_color = 8625919,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_snowy_taiga_mountains_d = {
	.name = "minecraft:snowy_taiga_mountains",
	.name_length = 31,
	.precipitation = mat_precipitation_snow,
	.depth = 0.3,
	.temperature = -0.5,
	.scale = 0.4,
	.downfall = 0.4,
	.category = mat_biome_category_taiga,
	.effects = {
		.sky_color = 8625919,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_snowy_tundra_d = {
	.name = "minecraft:snowy_tundra",
	.name_length = 22,
	.precipitation = mat_precipitation_snow,
	.depth = 0.125,
	.temperature = 0.0,
	.scale = 0.05,
	.downfall = 0.5,
	.category = mat_biome_category_icy,
	.effects = {
		.sky_color = 8364543,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_soul_sand_valley_d = {
	.name = "minecraft:soul_sand_valley",
	.name_length = 26,
	.precipitation = mat_precipitation_none,
	.depth = 0.1,
	.temperature = 2.0,
	.scale = 0.2,
	.downfall = 0.0,
	.category = mat_biome_category_nether,
	.effects = {
		.sky_color = 7254527,
		.water_fog_color = 329011,
		.fog_color = 1787717,
		.music = {
			.sound = "minecraft:music.nether.soul_sand_valley",
			.sound_length = 39,
			.max_delay = 24000,
			.min_delay = 12000,
		},
		.ambient_sound = "minecraft:ambient.soul_sand_valley.loop",
		.ambient_sound_length = 39,
		.additions_sound = {
			.sound = "minecraft:ambient.soul_sand_valley.additions",
			.sound_length = 44,
			.tick_chance = 0.0111,
		},
		.mood_sound = {
			.sound = "minecraft:ambient.soul_sand_valley.mood",
			.sound_length = 39,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
	.particle = {
		.probability = 0.00625,
		.options = {
			.type = "minecraft:ash",
			.type_length = 13,
		},
	},
};
const mat_biome_t mat_biome_stone_shore_d = {
	.name = "minecraft:stone_shore",
	.name_length = 21,
	.precipitation = mat_precipitation_rain,
	.depth = 0.1,
	.temperature = 0.2,
	.scale = 0.8,
	.downfall = 0.3,
	.category = mat_biome_category_none,
	.effects = {
		.sky_color = 8233727,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_sunflower_plains_d = {
	.name = "minecraft:sunflower_plains",
	.name_length = 26,
	.precipitation = mat_precipitation_rain,
	.depth = 0.125,
	.temperature = 0.8,
	.scale = 0.05,
	.downfall = 0.4,
	.category = mat_biome_category_plains,
	.effects = {
		.sky_color = 7907327,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_swamp_d = {
	.name = "minecraft:swamp",
	.name_length = 15,
	.precipitation = mat_precipitation_rain,
	.depth = -0.2,
	.temperature = 0.8,
	.scale = 0.1,
	.downfall = 0.9,
	.category = mat_biome_category_swamp,
	.effects = {
		.sky_color = 7907327,
		.water_fog_color = 2302743,
		.fog_color = 12638463,
		.has_foliage_color = true,
		.foliage_color = 6975545,
		.grass_color_modifier = mat_grass_color_modifier_swamp,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_swamp_hills_d = {
	.name = "minecraft:swamp_hills",
	.name_length = 21,
	.precipitation = mat_precipitation_rain,
	.depth = -0.1,
	.temperature = 0.8,
	.scale = 0.3,
	.downfall = 0.9,
	.category = mat_biome_category_swamp,
	.effects = {
		.sky_color = 7907327,
		.water_fog_color = 2302743,
		.fog_color = 12638463,
		.has_foliage_color = true,
		.foliage_color = 6975545,
		.grass_color_modifier = mat_grass_color_modifier_swamp,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_taiga_d = {
	.name = "minecraft:taiga",
	.name_length = 15,
	.precipitation = mat_precipitation_rain,
	.depth = 0.2,
	.temperature = 0.25,
	.scale = 0.2,
	.downfall = 0.8,
	.category = mat_biome_category_taiga,
	.effects = {
		.sky_color = 8233983,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_taiga_hills_d = {
	.name = "minecraft:taiga_hills",
	.name_length = 21,
	.precipitation = mat_precipitation_rain,
	.depth = 0.45,
	.temperature = 0.25,
	.scale = 0.3,
	.downfall = 0.8,
	.category = mat_biome_category_taiga,
	.effects = {
		.sky_color = 8233983,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_taiga_mountains_d = {
	.name = "minecraft:taiga_mountains",
	.name_length = 25,
	.precipitation = mat_precipitation_rain,
	.depth = 0.3,
	.temperature = 0.25,
	.scale = 0.4,
	.downfall = 0.8,
	.category = mat_biome_category_taiga,
	.effects = {
		.sky_color = 8233983,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_tall_birch_forest_d = {
	.name = "minecraft:tall_birch_forest",
	.name_length = 27,
	.precipitation = mat_precipitation_rain,
	.depth = 0.2,
	.temperature = 0.6,
	.scale = 0.4,
	.downfall = 0.6,
	.category = mat_biome_category_forest,
	.effects = {
		.sky_color = 8037887,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_tall_birch_hills_d = {
	.name = "minecraft:tall_birch_hills",
	.name_length = 26,
	.precipitation = mat_precipitation_rain,
	.depth = 0.55,
	.temperature = 0.6,
	.scale = 0.5,
	.downfall = 0.6,
	.category = mat_biome_category_forest,
	.effects = {
		.sky_color = 8037887,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_the_end_d = {
	.name = "minecraft:the_end",
	.name_length = 17,
	.precipitation = mat_precipitation_none,
	.depth = 0.1,
	.temperature = 0.5,
	.scale = 0.2,
	.downfall = 0.5,
	.category = mat_biome_category_the_end,
	.effects = {
		.sky_color = 0,
		.water_fog_color = 329011,
		.fog_color = 10518688,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_the_void_d = {
	.name = "minecraft:the_void",
	.name_length = 18,
	.precipitation = mat_precipitation_none,
	.depth = 0.1,
	.temperature = 0.5,
	.scale = 0.2,
	.downfall = 0.5,
	.category = mat_biome_category_none,
	.effects = {
		.sky_color = 8103167,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_warm_ocean_d = {
	.name = "minecraft:warm_ocean",
	.name_length = 20,
	.precipitation = mat_precipitation_rain,
	.depth = -1.0,
	.temperature = 0.5,
	.scale = 0.1,
	.downfall = 0.5,
	.category = mat_biome_category_ocean,
	.effects = {
		.sky_color = 8103167,
		.water_fog_color = 270131,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_warped_forest_d = {
	.name = "minecraft:warped_forest",
	.name_length = 23,
	.precipitation = mat_precipitation_none,
	.depth = 0.1,
	.temperature = 2.0,
	.scale = 0.2,
	.downfall = 0.0,
	.category = mat_biome_category_nether,
	.effects = {
		.sky_color = 7254527,
		.water_fog_color = 329011,
		.fog_color = 1705242,
		.music = {
			.sound = "minecraft:music.nether.warped_forest",
			.sound_length = 36,
			.max_delay = 24000,
			.min_delay = 12000,
		},
		.ambient_sound = "minecraft:ambient.warped_forest.loop",
		.ambient_sound_length = 36,
		.additions_sound = {
			.sound = "minecraft:ambient.warped_forest.additions",
			.sound_length = 41,
			.tick_chance = 0.0111,
		},
		.mood_sound = {
			.sound = "minecraft:ambient.warped_forest.mood",
			.sound_length = 36,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
	.particle = {
		.probability = 0.01428,
		.options = {
			.type = "minecraft:warped_spore",
			.type_length = 22,
		},
	},
};
const mat_biome_t mat_biome_wooded_badlands_plateau_d = {
	.name = "minecraft:wooded_badlands_plateau",
	.name_length = 33,
	.precipitation = mat_precipitation_none,
	.depth = 1.5,
	.temperature = 2.0,
	.scale = 0.025,
	.downfall = 0.0,
	.category = mat_biome_category_mesa,
	.effects = {
		.sky_color = 7254527,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.has_foliage_color = true,
		.foliage_color = 10387789,
		.has_grass_color = true,
		.grass_color = 9470285,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_wooded_hills_d = {
	.name = "minecraft:wooded_hills",
	.name_length = 22,
	.precipitation = mat_precipitation_rain,
	.depth = 0.45,
	.temperature = 0.7,
	.scale = 0.3,
	.downfall = 0.8,
	.category = mat_biome_category_forest,
	.effects = {
		.sky_color = 7972607,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t mat_biome_wooded_mountains_d = {
	.name = "minecraft:wooded_mountains",
	.name_length = 26,
	.precipitation = mat_precipitation_rain,
	.depth = 1.0,
	.temperature = 0.2,
	.scale = 0.5,
	.downfall = 0.3,
	.category = mat_biome_category_extreme_hills,
	.effects = {
		.sky_color = 8233727,
		.water_fog_color = 329011,
		.fog_color = 12638463,
		.mood_sound = {
			.sound = "minecraft:ambient.cave",
			.sound_length = 22,
			.offset = 2.0,
			.tick_delay = 6000,
			.block_search_extent = 8,
		},
	},
};
const mat_biome_t* mat_biomes[] = {
	&mat_biome_badlands_d,
	&mat_biome_badlands_plateau_d,
	&mat_biome_bamboo_jungle_d,
	&mat_biome_bamboo_jungle_hills_d,
	&mat_biome_basalt_deltas_d,
	&mat_biome_beach_d,
	&mat_biome_birch_forest_d,
	&mat_biome_birch_forest_hills_d,
	&mat_biome_cold_ocean_d,
	&mat_biome_crimson_forest_d,
	&mat_biome_dark_forest_d,
	&mat_biome_dark_forest_hills_d,
	&mat_biome_deep_cold_ocean_d,
	&mat_biome_deep_frozen_ocean_d,
	&mat_biome_deep_lukewarm_ocean_d,
	&mat_biome_deep_ocean_d,
	&mat_biome_deep_warm_ocean_d,
	&mat_biome_desert_d,
	&mat_biome_desert_hills_d,
	&mat_biome_desert_lakes_d,
	&mat_biome_dripstone_caves_d,
	&mat_biome_end_barrens_d,
	&mat_biome_end_highlands_d,
	&mat_biome_end_midlands_d,
	&mat_biome_eroded_badlands_d,
	&mat_biome_flower_forest_d,
	&mat_biome_forest_d,
	&mat_biome_frozen_ocean_d,
	&mat_biome_frozen_river_d,
	&mat_biome_giant_spruce_taiga_d,
	&mat_biome_giant_spruce_taiga_hills_d,
	&mat_biome_giant_tree_taiga_d,
	&mat_biome_giant_tree_taiga_hills_d,
	&mat_biome_gravelly_mountains_d,
	&mat_biome_ice_spikes_d,
	&mat_biome_jungle_d,
	&mat_biome_jungle_edge_d,
	&mat_biome_jungle_hills_d,
	&mat_biome_lukewarm_ocean_d,
	&mat_biome_lush_caves_d,
	&mat_biome_modified_badlands_plateau_d,
	&mat_biome_modified_gravelly_mountains_d,
	&mat_biome_modified_jungle_d,
	&mat_biome_modified_jungle_edge_d,
	&mat_biome_modified_wooded_badlands_plateau_d,
	&mat_biome_mountains_d,
	&mat_biome_mountain_edge_d,
	&mat_biome_mushroom_fields_d,
	&mat_biome_mushroom_field_shore_d,
	&mat_biome_nether_wastes_d,
	&mat_biome_ocean_d,
	&mat_biome_plains_d,
	&mat_biome_river_d,
	&mat_biome_savanna_d,
	&mat_biome_savanna_plateau_d,
	&mat_biome_shattered_savanna_d,
	&mat_biome_shattered_savanna_plateau_d,
	&mat_biome_small_end_islands_d,
	&mat_biome_snowy_beach_d,
	&mat_biome_snowy_mountains_d,
	&mat_biome_snowy_taiga_d,
	&mat_biome_snowy_taiga_hills_d,
	&mat_biome_snowy_taiga_mountains_d,
	&mat_biome_snowy_tundra_d,
	&mat_biome_soul_sand_valley_d,
	&mat_biome_stone_shore_d,
	&mat_biome_sunflower_plains_d,
	&mat_biome_swamp_d,
	&mat_biome_swamp_hills_d,
	&mat_biome_taiga_d,
	&mat_biome_taiga_hills_d,
	&mat_biome_taiga_mountains_d,
	&mat_biome_tall_birch_forest_d,
	&mat_biome_tall_birch_hills_d,
	&mat_biome_the_end_d,
	&mat_biome_the_void_d,
	&mat_biome_warm_ocean_d,
	&mat_biome_warped_forest_d,
	&mat_biome_wooded_badlands_plateau_d,
	&mat_biome_wooded_hills_d,
	&mat_biome_wooded_mountains_d,
};
