#pragma once
#include "../../main.h"
#include "../../util/bitset.h"

/*
	HITBOX
	Hitboxes are used for physics to determine collisions
*/

typedef enum {

	mat_hitbox_none = -1,
	mat_hitbox_full

} mat_hitbox_id_t;

typedef struct {

	size_t count;

	struct {

		float32_t x, y, z, width, height, depth;
	
	} hitbox[];

} mat_hitbox_t;

extern const mat_hitbox_t* mat_hitboxes[];

static inline const mat_hitbox_t* mat_getHitboxById(mat_hitbox_id_t hitbox) {
	return mat_hitboxes[hitbox];
}

/*
	STATE MODIFIERS
	State modifiers are used to determine the state
*/

typedef enum {

	mat_state_modifier_facing_cardinal,
	mat_state_modifier_bamboo_age,
	mat_state_modifier_bamboo_leaves,
	mat_state_modifier_bamboo_state
	// TODO automatically generate this

} mat_state_modifier_type_t;

typedef struct {

	size_t count;

	struct {

		mat_hitbox_id_t hitbox;

	} state[];

} mat_state_modifier_t;

extern const mat_state_modifier_t mat_modifiers[];

static inline const mat_state_modifier_t* mat_getStateModifierByType(mat_state_modifier_type_t type) {
	return mat_modifiers + type;
}

/*
	Equipment
	Equipment are used to determine breaking speed and drops
	They:
	- Have a max durability
	- Only appear in stacks of one
*/

typedef enum {

	mat_equipment_type_any = 0,

	mat_equipment_type_sword,
	mat_equipment_type_axe,
	mat_equipment_type_pickaxe,
	mat_equipment_type_shovel,
	mat_equipment_type_hoe,
	
	// shears do no additional damage but have breaking time boosts
	mat_equipment_type_shears,
	
	// tridents have no breaking time benefit but still do melee damage
	mat_equipment_type_trident,

	mat_equipment_type_bow,
	mat_equipment_type_crossbow,
	mat_equipment_type_fishing_rod,
	mat_equipment_type_flint_and_steel,

	// everything helmet and above has different properties
	// (instead of attack speed and damage, armor toughness and defense)

	mat_equipment_type_helmet,
	mat_equipment_type_chestplate,
	mat_equipment_type_leggings,
	mat_equipment_type_boots,
	mat_equipment_type_shield

} mat_equipment_type_t;

typedef enum {

	mat_equipment_tier_any = 0,

	mat_equipment_tier_leather,
	mat_equipment_tier_wood,
	mat_equipment_tier_stone,
	mat_equipment_tier_gold,
	mat_equipment_tier_iron,
	mat_equipment_tier_diamond,
	mat_equipment_tier_netherite

} mat_equipment_tier_t;

/*
	BLOCK ENTITIES
	Block entities are used to store extra information that couldn't be stored in states
*/

typedef enum {

	mat_block_entity_none = 0,
	mat_block_entity_type_sign,
	mat_block_entity_type_banner,
	mat_block_entity_type_storage,
	mat_block_entity_type_furnace,
	mat_block_entity_type_brewing_stand,
	mat_block_entity_type_hopper,
	mat_block_entity_type_chest,
	mat_block_entity_type_beacon,
	mat_block_entity_type_monster_spawner,
	mat_block_entity_type_note_block,
	mat_block_entity_type_piston,
	mat_block_entity_type_jukebox,
	mat_block_entity_type_enchantment_table,
	mat_block_entity_type_particle,
	mat_block_entity_type_mob_head,
	mat_block_entity_type_command_block,
	mat_block_entity_type_end_gateway,
	mat_block_entity_type_structure_block,
	mat_block_entity_type_daylight_sensor,
	mat_block_entity_type_flower_pot,
	mat_block_entity_type_redstone_comparator

} mat_block_entity_type_t;

/*
	BLOCKS
	Blocks are the basic building blocks of the world
*/

typedef enum {

	mat_block_acacia_button,
	mat_block_acacia_door,
	mat_block_acacia_fence,
	mat_block_acacia_fence_gate,
	mat_block_acacia_leaves,
	mat_block_acacia_log,
	mat_block_acacia_planks,
	mat_block_acacia_pressure_plate,
	mat_block_acacia_sapling,
	mat_block_acacia_sign,
	mat_block_acacia_slab,
	mat_block_acacia_stairs,
	mat_block_acacia_trapdoor,
	mat_block_acacia_wood,
	mat_block_activator_rail,
	mat_block_allium,
	mat_block_amethyst_cluster,
	mat_block_ancient_debris,
	mat_block_andesite,
	mat_block_andesite_slab,
	mat_block_andesite_stairs,
	mat_block_andesite_wall,
	mat_block_anvil,
	mat_block_azalea,
	mat_block_azalea_leaves,
	mat_block_azure_bluet,
	mat_block_bamboo,
	mat_block_bamboo_shoot,
	mat_block_beetroots,
	mat_block_barrel,
	mat_block_barrier,
	mat_block_basalt,
	mat_block_beacon,
	mat_block_bedrock,
	mat_block_beehive,
	mat_block_bee_nest,
	mat_block_bell,
	mat_block_big_dripleaf,
	mat_block_birch_button,
	mat_block_birch_door,
	mat_block_birch_fence,
	mat_block_birch_fence_gate,
	mat_block_birch_leaves,
	mat_block_birch_log,
	mat_block_birch_planks,
	mat_block_birch_pressure_plate,
	mat_block_birch_sapling,
	mat_block_birch_sign,
	mat_block_birch_slab,
	mat_block_birch_stairs,
	mat_block_birch_trapdoor,
	mat_block_birch_wood,
	mat_block_black_banner,
	mat_block_black_bed,
	mat_block_black_candle,
	mat_block_black_carpet,
	mat_block_black_concrete,
	mat_block_black_concrete_powder,
	mat_block_black_glazed_terracotta,
	mat_block_black_shulker_box,
	mat_block_black_stained_glass,
	mat_block_black_stained_glass_pane,
	mat_block_black_terracotta,
	mat_block_black_wool,
	mat_block_blackstone,
	mat_block_blackstone_slab,
	mat_block_blackstone_stairs,
	mat_block_blackstone_wall,
	mat_block_blast_furnace,
	mat_block_block_of_amethyst,
	mat_block_block_of_coal,
	mat_block_block_of_copper,
	mat_block_block_of_diamond,
	mat_block_block_of_emerald,
	mat_block_block_of_gold,
	mat_block_block_of_iron,
	mat_block_block_of_lapis_lazuli,
	mat_block_block_of_netherite,
	mat_block_block_of_quartz,
	mat_block_block_of_raw_copper,
	mat_block_block_of_raw_gold,
	mat_block_block_of_raw_iron,
	mat_block_block_of_redstone,
	mat_block_blue_banner,
	mat_block_blue_bed,
	mat_block_blue_candle,
	mat_block_blue_carpet,
	mat_block_blue_concrete,
	mat_block_blue_concrete_powder,
	mat_block_blue_glazed_terracotta,
	mat_block_blue_ice,
	mat_block_blue_orchid,
	mat_block_blue_shulker_box,
	mat_block_blue_stained_glass,
	mat_block_blue_stained_glass_pane,
	mat_block_blue_terracotta,
	mat_block_blue_wool,
	mat_block_bone_block,
	mat_block_bookshelf,
	mat_block_brain_coral,
	mat_block_brain_coral_block,
	mat_block_brain_coral_fan,
	mat_block_brewing_stand,
	mat_block_brick_slab,
	mat_block_brick_stairs,
	mat_block_brick_wall,
	mat_block_bricks,
	mat_block_brown_banner,
	mat_block_brown_bed,
	mat_block_brown_candle,
	mat_block_brown_carpet,
	mat_block_brown_concrete,
	mat_block_brown_concrete_powder,
	mat_block_brown_glazed_terracotta,
	mat_block_brown_mushroom,
	mat_block_brown_mushroom_block,
	mat_block_brown_shulker_box,
	mat_block_brown_stained_glass,
	mat_block_brown_stained_glass_pane,
	mat_block_brown_terracotta,
	mat_block_brown_wool,
	mat_block_bubble_coral,
	mat_block_bubble_coral_block,
	mat_block_bubble_coral_fan,
	mat_block_budding_amethyst,
	mat_block_cactus,
	mat_block_cake,
	mat_block_calcite,
	mat_block_campfire,
	mat_block_candle,
	mat_block_carrots,
	mat_block_cartography_table,
	mat_block_carved_pumpkin,
	mat_block_cauldron,
	mat_block_cave_vines,
	mat_block_chain,
	mat_block_chain_command_block,
	mat_block_chest,
	mat_block_chipped_anvil,
	mat_block_chiseled_deepslate,
	mat_block_chiseled_nether_bricks,
	mat_block_chiseled_polished_blackstone,
	mat_block_chiseled_quartz_block,
	mat_block_chiseled_red_sandstone,
	mat_block_chiseled_sandstone,
	mat_block_chiseled_stone_bricks,
	mat_block_chorus_flower,
	mat_block_chorus_plant,
	mat_block_clay,
	mat_block_coal_ore,
	mat_block_coarse_dirt,
	mat_block_cobbled_deepslate,
	mat_block_cobbled_deepslate_slab,
	mat_block_cobbled_deepslate_stairs,
	mat_block_cobbled_deepslate_wall,
	mat_block_cobblestone,
	mat_block_cobblestone_slab,
	mat_block_cobblestone_stairs,
	mat_block_cobblestone_wall,
	mat_block_cobweb,
	mat_block_cocoa,
	mat_block_command_block,
	mat_block_composter,
	mat_block_conduit,
	mat_block_copper_ore,
	mat_block_cornflower,
	mat_block_cracked_deepslate_bricks,
	mat_block_cracked_deepslate_tiles,
	mat_block_cracked_nether_bricks,
	mat_block_cracked_polished_blackstone_bricks,
	mat_block_cracked_stone_bricks,
	mat_block_crafting_table,
	mat_block_creeper_head,
	mat_block_crimson_button,
	mat_block_crimson_door,
	mat_block_crimson_fence,
	mat_block_crimson_fence_gate,
	mat_block_crimson_fungus,
	mat_block_crimson_hyphae,
	mat_block_crimson_nylium,
	mat_block_crimson_planks,
	mat_block_crimson_pressure_plate,
	mat_block_crimson_roots,
	mat_block_crimson_sign,
	mat_block_crimson_slab,
	mat_block_crimson_stairs,
	mat_block_crimson_stem,
	mat_block_crimson_trapdoor,
	mat_block_crying_obsidian,
	mat_block_cut_copper,
	mat_block_cut_copper_slab,
	mat_block_cut_copper_stairs,
	mat_block_cut_red_sandstone,
	mat_block_cut_red_sandstone_slab,
	mat_block_cut_sandstone,
	mat_block_cut_sandstone_slab,
	mat_block_cyan_banner,
	mat_block_cyan_bed,
	mat_block_cyan_candle,
	mat_block_cyan_carpet,
	mat_block_cyan_concrete,
	mat_block_cyan_concrete_powder,
	mat_block_cyan_glazed_terracotta,
	mat_block_cyan_shulker_box,
	mat_block_cyan_stained_glass,
	mat_block_cyan_stained_glass_pane,
	mat_block_cyan_terracotta,
	mat_block_cyan_wool,
	mat_block_damaged_anvil,
	mat_block_dandelion,
	mat_block_dark_oak_button,
	mat_block_dark_oak_door,
	mat_block_dark_oak_fence,
	mat_block_dark_oak_fence_gate,
	mat_block_dark_oak_leaves,
	mat_block_dark_oak_log,
	mat_block_dark_oak_planks,
	mat_block_dark_oak_pressure_plate,
	mat_block_dark_oak_sapling,
	mat_block_dark_oak_sign,
	mat_block_dark_oak_slab,
	mat_block_dark_oak_stairs,
	mat_block_dark_oak_trapdoor,
	mat_block_dark_oak_wood,
	mat_block_dark_prismarine,
	mat_block_dark_prismarine_slab,
	mat_block_dark_prismarine_stairs,
	mat_block_daylight_detector,
	mat_block_dead_brain_coral,
	mat_block_dead_brain_coral_block,
	mat_block_dead_brain_coral_fan,
	mat_block_dead_bubble_coral,
	mat_block_dead_bubble_coral_block,
	mat_block_dead_bubble_coral_fan,
	mat_block_dead_bush,
	mat_block_dead_fire_coral,
	mat_block_dead_fire_coral_block,
	mat_block_dead_fire_coral_fan,
	mat_block_dead_horn_coral,
	mat_block_dead_horn_coral_block,
	mat_block_dead_horn_coral_fan,
	mat_block_dead_tube_coral,
	mat_block_dead_tube_coral_block,
	mat_block_dead_tube_coral_fan,
	mat_block_deepslate,
	mat_block_deepslate_bricks,
	mat_block_deepslate_brick_slab,
	mat_block_deepslate_brick_stairs,
	mat_block_deepslate_brick_wall,
	mat_block_deepslate_coal_ore,
	mat_block_deepslate_copper_ore,
	mat_block_deepslate_diamond_ore,
	mat_block_deepslate_emerald_ore,
	mat_block_deepslate_gold_ore,
	mat_block_deepslate_iron_ore,
	mat_block_deepslate_lapis_lazuli_ore,
	mat_block_deepslate_redstone_ore,
	mat_block_deepslate_tiles,
	mat_block_deepslate_tile_slab,
	mat_block_deepslate_tile_stairs,
	mat_block_deepslate_tile_wall,
	mat_block_detector_rail,
	mat_block_diamond_ore,
	mat_block_diorite,
	mat_block_diorite_slab,
	mat_block_diorite_stairs,
	mat_block_diorite_wall,
	mat_block_dirt,
	mat_block_dirt_path,
	mat_block_dispenser,
	mat_block_dragon_egg,
	mat_block_dragon_head,
	mat_block_dried_kelp_block,
	mat_block_dripstone_block,
	mat_block_dropper,
	mat_block_emerald_ore,
	mat_block_enchanting_table,
	mat_block_end_portal_frame,
	mat_block_end_rod,
	mat_block_end_stone,
	mat_block_end_stone_brick_slab,
	mat_block_end_stone_brick_stairs,
	mat_block_end_stone_brick_wall,
	mat_block_end_stone_bricks,
	mat_block_ender_chest,
	mat_block_exposed_copper,
	mat_block_exposed_cut_copper,
	mat_block_exposed_cut_copper_slab,
	mat_block_exposed_cut_copper_stairs,
	mat_block_farmland,
	mat_block_fern,
	mat_block_fire,
	mat_block_fire_coral,
	mat_block_fire_coral_block,
	mat_block_fire_coral_fan,
	mat_block_fletching_table,
	mat_block_flower_pot,
	mat_block_flowering_azalea,
	mat_block_flowering_azalea_leaves,
	mat_block_furnace,
	mat_block_gilded_blackstone,
	mat_block_glass,
	mat_block_glass_pane,
	mat_block_glow_lichen,
	mat_block_glowstone,
	mat_block_gold_ore,
	mat_block_granite,
	mat_block_granite_slab,
	mat_block_granite_stairs,
	mat_block_granite_wall,
	mat_block_grass,
	mat_block_grass_block,
	mat_block_gravel,
	mat_block_gray_banner,
	mat_block_gray_bed,
	mat_block_gray_candle,
	mat_block_gray_carpet,
	mat_block_gray_concrete,
	mat_block_gray_concrete_powder,
	mat_block_gray_glazed_terracotta,
	mat_block_gray_shulker_box,
	mat_block_gray_stained_glass,
	mat_block_gray_stained_glass_pane,
	mat_block_gray_terracotta,
	mat_block_gray_wool,
	mat_block_green_banner,
	mat_block_green_bed,
	mat_block_green_candle,
	mat_block_green_carpet,
	mat_block_green_concrete,
	mat_block_green_concrete_powder,
	mat_block_green_glazed_terracotta,
	mat_block_green_shulker_box,
	mat_block_green_stained_glass,
	mat_block_green_stained_glass_pane,
	mat_block_green_terracotta,
	mat_block_green_wool,
	mat_block_grindstone,
	mat_block_hanging_roots,
	mat_block_hay_bale,
	mat_block_heavy_weighted_pressure_plate,
	mat_block_honey_block,
	mat_block_honeycomb_block,
	mat_block_hopper,
	mat_block_horn_coral,
	mat_block_horn_coral_block,
	mat_block_horn_coral_fan,
	mat_block_ice,
	mat_block_infested_chiseled_stone_bricks,
	mat_block_infested_cobblestone,
	mat_block_infested_cracked_stone_bricks,
	mat_block_infested_deepslate,
	mat_block_infested_mossy_stone_bricks,
	mat_block_infested_stone,
	mat_block_infested_stone_bricks,
	mat_block_iron_bars,
	mat_block_iron_door,
	mat_block_iron_ore,
	mat_block_iron_trapdoor,
	mat_block_jack_o_lantern,
	mat_block_jigsaw_block,
	mat_block_jukebox,
	mat_block_jungle_button,
	mat_block_jungle_door,
	mat_block_jungle_fence,
	mat_block_jungle_fence_gate,
	mat_block_jungle_leaves,
	mat_block_jungle_log,
	mat_block_jungle_planks,
	mat_block_jungle_pressure_plate,
	mat_block_jungle_sapling,
	mat_block_jungle_sign,
	mat_block_jungle_slab,
	mat_block_jungle_stairs,
	mat_block_jungle_trapdoor,
	mat_block_jungle_wood,
	mat_block_kelp,
	mat_block_ladder,
	mat_block_lantern,
	mat_block_lapis_lazuli_ore,
	mat_block_large_amethyst_bud,
	mat_block_large_fern,
	mat_block_lava,
	mat_block_lectern,
	mat_block_lever,
	mat_block_light_block,
	mat_block_light_blue_banner,
	mat_block_light_blue_bed,
	mat_block_light_blue_candle,
	mat_block_light_blue_carpet,
	mat_block_light_blue_concrete,
	mat_block_light_blue_concrete_powder,
	mat_block_light_blue_glazed_terracotta,
	mat_block_light_blue_shulker_box,
	mat_block_light_blue_stained_glass,
	mat_block_light_blue_stained_glass_pane,
	mat_block_light_blue_terracotta,
	mat_block_light_blue_wool,
	mat_block_light_gray_banner,
	mat_block_light_gray_bed,
	mat_block_light_gray_candle,
	mat_block_light_gray_carpet,
	mat_block_light_gray_concrete,
	mat_block_light_gray_concrete_powder,
	mat_block_light_gray_glazed_terracotta,
	mat_block_light_gray_shulker_box,
	mat_block_light_gray_stained_glass,
	mat_block_light_gray_stained_glass_pane,
	mat_block_light_gray_terracotta,
	mat_block_light_gray_wool,
	mat_block_light_weighted_pressure_plate,
	mat_block_lightning_rod,
	mat_block_lilac,
	mat_block_lily_of_the_valley,
	mat_block_lily_pad,
	mat_block_lime_banner,
	mat_block_lime_bed,
	mat_block_lime_candle,
	mat_block_lime_carpet,
	mat_block_lime_concrete,
	mat_block_lime_concrete_powder,
	mat_block_lime_glazed_terracotta,
	mat_block_lime_shulker_box,
	mat_block_lime_stained_glass,
	mat_block_lime_stained_glass_pane,
	mat_block_lime_terracotta,
	mat_block_lime_wool,
	mat_block_lodestone,
	mat_block_loom,
	mat_block_magenta_banner,
	mat_block_magenta_bed,
	mat_block_magenta_candle,
	mat_block_magenta_carpet,
	mat_block_magenta_concrete,
	mat_block_magenta_concrete_powder,
	mat_block_magenta_glazed_terracotta,
	mat_block_magenta_shulker_box,
	mat_block_magenta_stained_glass,
	mat_block_magenta_stained_glass_pane,
	mat_block_magenta_terracotta,
	mat_block_magenta_wool,
	mat_block_magma_block,
	mat_block_medium_amethyst_bud,
	mat_block_melon,
	mat_block_melon_stem,
	mat_block_moss_block,
	mat_block_moss_carpet,
	mat_block_mossy_cobblestone,
	mat_block_mossy_cobblestone_slab,
	mat_block_mossy_cobblestone_stairs,
	mat_block_mossy_cobblestone_wall,
	mat_block_mossy_stone_brick_slab,
	mat_block_mossy_stone_brick_stairs,
	mat_block_mossy_stone_brick_wall,
	mat_block_mossy_stone_bricks,
	mat_block_mushroom_stem,
	mat_block_mycelium,
	mat_block_nether_brick_fence,
	mat_block_nether_brick_slab,
	mat_block_nether_brick_stairs,
	mat_block_nether_brick_wall,
	mat_block_nether_bricks,
	mat_block_nether_gold_ore,
	mat_block_nether_quartz_ore,
	mat_block_nether_sprouts,
	mat_block_nether_wart,
	mat_block_nether_wart_block,
	mat_block_netherrack,
	mat_block_note_block,
	mat_block_oak_button,
	mat_block_oak_door,
	mat_block_oak_fence,
	mat_block_oak_fence_gate,
	mat_block_oak_leaves,
	mat_block_oak_log,
	mat_block_oak_planks,
	mat_block_oak_pressure_plate,
	mat_block_oak_sapling,
	mat_block_oak_sign,
	mat_block_oak_slab,
	mat_block_oak_stairs,
	mat_block_oak_trapdoor,
	mat_block_oak_wood,
	mat_block_observer,
	mat_block_obsidian,
	mat_block_ominous_banner,
	mat_block_orange_banner,
	mat_block_orange_bed,
	mat_block_orange_candle,
	mat_block_orange_carpet,
	mat_block_orange_concrete,
	mat_block_orange_concrete_powder,
	mat_block_orange_glazed_terracotta,
	mat_block_orange_shulker_box,
	mat_block_orange_stained_glass,
	mat_block_orange_stained_glass_pane,
	mat_block_orange_terracotta,
	mat_block_orange_tulip,
	mat_block_orange_wool,
	mat_block_oxeye_daisy,
	mat_block_oxidized_copper,
	mat_block_oxidized_cut_copper,
	mat_block_oxidized_cut_copper_slab,
	mat_block_oxidized_cut_copper_stairs,
	mat_block_packed_ice,
	mat_block_peony,
	mat_block_petrified_oak_slab,
	mat_block_pink_banner,
	mat_block_pink_bed,
	mat_block_pink_candle,
	mat_block_pink_carpet,
	mat_block_pink_concrete,
	mat_block_pink_concrete_powder,
	mat_block_pink_glazed_terracotta,
	mat_block_pink_shulker_box,
	mat_block_pink_stained_glass,
	mat_block_pink_stained_glass_pane,
	mat_block_pink_terracotta,
	mat_block_pink_tulip,
	mat_block_pink_wool,
	mat_block_piston,
	mat_block_player_head,
	mat_block_podzol,
	mat_block_pointed_dripstone,
	mat_block_polished_andesite,
	mat_block_polished_andesite_slab,
	mat_block_polished_andesite_stairs,
	mat_block_polished_basalt,
	mat_block_polished_blackstone,
	mat_block_polished_blackstone_brick_slab,
	mat_block_polished_blackstone_brick_stairs,
	mat_block_polished_blackstone_brick_wall,
	mat_block_polished_blackstone_bricks,
	mat_block_polished_blackstone_button,
	mat_block_polished_blackstone_pressure_plate,
	mat_block_polished_blackstone_slab,
	mat_block_polished_blackstone_stairs,
	mat_block_polished_blackstone_wall,
	mat_block_polished_diorite,
	mat_block_polished_diorite_slab,
	mat_block_polished_diorite_stairs,
	mat_block_polished_granite,
	mat_block_polished_granite_slab,
	mat_block_polished_granite_stairs,
	mat_block_polished_deepslate,
	mat_block_polished_deepslate_slab,
	mat_block_polished_deepslate_stairs,
	mat_block_polished_deepslate_wall,
	mat_block_poppy,
	mat_block_potatoes,
	mat_block_powder_snow,
	mat_block_powered_rail,
	mat_block_prismarine,
	mat_block_prismarine_brick_slab,
	mat_block_prismarine_brick_stairs,
	mat_block_prismarine_bricks,
	mat_block_prismarine_slab,
	mat_block_prismarine_stairs,
	mat_block_prismarine_wall,
	mat_block_pumpkin,
	mat_block_pumpkin_stem,
	mat_block_purple_banner,
	mat_block_purple_bed,
	mat_block_purple_candle,
	mat_block_purple_carpet,
	mat_block_purple_concrete,
	mat_block_purple_concrete_powder,
	mat_block_purple_glazed_terracotta,
	mat_block_purple_shulker_box,
	mat_block_purple_stained_glass,
	mat_block_purple_stained_glass_pane,
	mat_block_purple_terracotta,
	mat_block_purple_wool,
	mat_block_purpur_block,
	mat_block_purpur_pillar,
	mat_block_purpur_slab,
	mat_block_purpur_stairs,
	mat_block_quartz_bricks,
	mat_block_quartz_pillar,
	mat_block_quartz_slab,
	mat_block_quartz_stairs,
	mat_block_rail,
	mat_block_red_banner,
	mat_block_red_bed,
	mat_block_red_candle,
	mat_block_red_carpet,
	mat_block_red_concrete,
	mat_block_red_concrete_powder,
	mat_block_red_glazed_terracotta,
	mat_block_red_mushroom,
	mat_block_red_mushroom_block,
	mat_block_red_nether_brick_slab,
	mat_block_red_nether_brick_stairs,
	mat_block_red_nether_brick_wall,
	mat_block_red_nether_bricks,
	mat_block_red_sand,
	mat_block_red_sandstone,
	mat_block_red_sandstone_slab,
	mat_block_red_sandstone_stairs,
	mat_block_red_sandstone_wall,
	mat_block_red_shulker_box,
	mat_block_red_stained_glass,
	mat_block_red_stained_glass_pane,
	mat_block_red_terracotta,
	mat_block_red_tulip,
	mat_block_red_wool,
	mat_block_redstone_comparator,
	mat_block_redstone_lamp,
	mat_block_redstone_ore,
	mat_block_redstone_repeater,
	mat_block_redstone_torch,
	mat_block_redstone_wire,
	mat_block_repeating_command_block,
	mat_block_respawn_anchor,
	mat_block_rooted_dirt,
	mat_block_rose_bush,
	mat_block_sand,
	mat_block_sandstone,
	mat_block_sandstone_slab,
	mat_block_sandstone_stairs,
	mat_block_sandstone_wall,
	mat_block_scaffolding,
	mat_block_sculk_sensor,
	mat_block_sea_lantern,
	mat_block_sea_pickle,
	mat_block_seagrass,
	mat_block_shroomlight,
	mat_block_shulker_box,
	mat_block_skeleton_skull,
	mat_block_slime_block,
	mat_block_small_amethyst_bud,
	mat_block_small_dripleaf,
	mat_block_smithing_table,
	mat_block_smoker,
	mat_block_smooth_basalt,
	mat_block_smooth_quartz_block,
	mat_block_smooth_quartz_slab,
	mat_block_smooth_quartz_stairs,
	mat_block_smooth_red_sandstone,
	mat_block_smooth_red_sandstone_slab,
	mat_block_smooth_red_sandstone_stairs,
	mat_block_smooth_sandstone,
	mat_block_smooth_sandstone_slab,
	mat_block_smooth_sandstone_stairs,
	mat_block_smooth_stone,
	mat_block_smooth_stone_slab,
	mat_block_snow,
	mat_block_snow_block,
	mat_block_soul_campfire,
	mat_block_soul_fire,
	mat_block_soul_lantern,
	mat_block_soul_sand,
	mat_block_soul_soil,
	mat_block_soul_torch,
	mat_block_spawner,
	mat_block_sponge,
	mat_block_spore_blossom,
	mat_block_spruce_button,
	mat_block_spruce_door,
	mat_block_spruce_fence,
	mat_block_spruce_fence_gate,
	mat_block_spruce_leaves,
	mat_block_spruce_log,
	mat_block_spruce_planks,
	mat_block_spruce_pressure_plate,
	mat_block_spruce_sapling,
	mat_block_spruce_sign,
	mat_block_spruce_slab,
	mat_block_spruce_stairs,
	mat_block_spruce_trapdoor,
	mat_block_spruce_wood,
	mat_block_sticky_piston,
	mat_block_stone,
	mat_block_stone_brick_slab,
	mat_block_stone_brick_stairs,
	mat_block_stone_brick_wall,
	mat_block_stone_bricks,
	mat_block_stone_button,
	mat_block_stone_pressure_plate,
	mat_block_stone_slab,
	mat_block_stone_stairs,
	mat_block_stonecutter,
	mat_block_stripped_acacia_log,
	mat_block_stripped_acacia_wood,
	mat_block_stripped_birch_log,
	mat_block_stripped_birch_wood,
	mat_block_stripped_crimson_hyphae,
	mat_block_stripped_crimson_stem,
	mat_block_stripped_dark_oak_log,
	mat_block_stripped_dark_oak_wood,
	mat_block_stripped_jungle_log,
	mat_block_stripped_jungle_wood,
	mat_block_stripped_oak_log,
	mat_block_stripped_oak_wood,
	mat_block_stripped_spruce_log,
	mat_block_stripped_spruce_wood,
	mat_block_stripped_warped_hyphae,
	mat_block_stripped_warped_stem,
	mat_block_structure_block,
	mat_block_structure_void,
	mat_block_sugar_cane,
	mat_block_sunflower,
	mat_block_sweet_berry_bush,
	mat_block_tall_grass,
	mat_block_tall_seagrass,
	mat_block_target,
	mat_block_terracotta,
	mat_block_tinted_glass,
	mat_block_tnt,
	mat_block_torch,
	mat_block_trapped_chest,
	mat_block_tripwire,
	mat_block_tripwire_hook,
	mat_block_tube_coral,
	mat_block_tube_coral_block,
	mat_block_tube_coral_fan,
	mat_block_tuff,
	mat_block_turtle_egg,
	mat_block_twisting_vines,
	mat_block_vines,
	mat_block_warped_button,
	mat_block_warped_door,
	mat_block_warped_fence,
	mat_block_warped_fence_gate,
	mat_block_warped_fungus,
	mat_block_warped_hyphae,
	mat_block_warped_nylium,
	mat_block_warped_planks,
	mat_block_warped_pressure_plate,
	mat_block_warped_roots,
	mat_block_warped_sign,
	mat_block_warped_slab,
	mat_block_warped_stairs,
	mat_block_warped_stem,
	mat_block_warped_trapdoor,
	mat_block_warped_wart_block,
	mat_block_water,
	mat_block_waxed_block_of_copper,
	mat_block_waxed_cut_copper,
	mat_block_waxed_cut_copper_slab,
	mat_block_waxed_cut_copper_stairs,
	mat_block_waxed_exposed_copper,
	mat_block_waxed_exposed_cut_copper,
	mat_block_waxed_exposed_cut_copper_slab,
	mat_block_waxed_exposed_cut_copper_stairs,
	mat_block_waxed_oxidized_copper,
	mat_block_waxed_oxidized_cut_copper,
	mat_block_waxed_oxidized_cut_copper_slab,
	mat_block_waxed_oxidized_cut_copper_stairs,
	mat_block_waxed_weathered_copper,
	mat_block_waxed_weathered_cut_copper,
	mat_block_waxed_weathered_cut_copper_slab,
	mat_block_waxed_weathered_cut_copper_stairs,
	mat_block_weathered_copper,
	mat_block_weathered_cut_copper,
	mat_block_weathered_cut_copper_slab,
	mat_block_weathered_cut_copper_stairs,
	mat_block_weeping_vines,
	mat_block_wet_sponge,
	mat_block_wheat_crops,
	mat_block_white_banner,
	mat_block_white_bed,
	mat_block_white_candle,
	mat_block_white_carpet,
	mat_block_white_concrete,
	mat_block_white_concrete_powder,
	mat_block_white_glazed_terracotta,
	mat_block_white_shulker_box,
	mat_block_white_stained_glass,
	mat_block_white_stained_glass_pane,
	mat_block_white_terracotta,
	mat_block_white_tulip,
	mat_block_white_wool,
	mat_block_wither_rose,
	mat_block_wither_skeleton_skull,
	mat_block_yellow_banner,
	mat_block_yellow_bed,
	mat_block_yellow_candle,
	mat_block_yellow_carpet,
	mat_block_yellow_concrete,
	mat_block_yellow_concrete_powder,
	mat_block_yellow_glazed_terracotta,
	mat_block_yellow_shulker_box,
	mat_block_yellow_stained_glass,
	mat_block_yellow_stained_glass_pane,
	mat_block_yellow_terracotta,
	mat_block_yellow_wool,
	mat_block_zombie_head

} mat_block_id_t;

typedef struct {

	float32_t resistance;
		// blast resistance

	float32_t hardness;
		// hardness value for calculating break times

	uint8_t light;
		// First 4 bits: luminance (0 = no light)
		// Last 4 bits: transparency (0 = blocks all light)

	uint8_t encouragement;
		// most significant bit = can catch fire from lava
	uint8_t flammability;
		// most significant bit = can burn away

	struct {
		
		mat_equipment_type_t type;
		mat_equipment_tier_t tier;

	} best_tool;

	mat_block_entity_type_t entity;

	struct {

		size_t count;
		mat_state_modifier_type_t modifier[];

	} modifiers;

} mat_block_t;

extern const mat_block_t* mat_blocks[];
extern const mat_block_id_t mat_blocks_protocol[];

static inline const mat_block_t* mat_getBlockById(mat_block_id_t id) {
	return mat_blocks[id];
}

static inline uint8_t mat_getLuminance(const mat_block_t* block) {

	return block->light >> 4;

}

static inline uint8_t mat_getTransparency(const mat_block_t* block) {

	return block->light & 0xF;

}

static inline bool_t utl_catchesFireFromLava(const mat_block_t* block) {

	return (block->encouragement & 0x80) ? true : false;

}

static inline bool_t utl_canBurnAway(const mat_block_t* block) {

	return (block->flammability & 0x80) ? true : false;

}

static inline uint8_t utl_getEncouragement(const mat_block_t* block) {

	return block->encouragement & 0x7F;

}

static inline uint8_t utl_getFlammability(const mat_block_t* block) {

	return block->flammability & 0x7F;

}

/*
	ITEMS
	Every single item in minecraft
*/

typedef enum {

	mat_item_acacia_boat,
	mat_item_armor_stand,
	mat_item_beetroot_seeds,
	mat_item_birch_boat,
	mat_item_bottle_o_enchanting,
	mat_item_bow,
	mat_item_bucket,
	mat_item_bucket_of_axolotl,
	mat_item_bucket_of_cod,
	mat_item_bucket_of_pufferfish,
	mat_item_bucket_of_salmon,
	mat_item_bucket_of_tropical_fish,
	mat_item_carrot,
	mat_item_cocoa_beans,
	mat_item_crossbow,
	mat_item_dark_oak_boat,
	mat_item_egg,
	mat_item_end_crystal,
	mat_item_ender_pearl,
	mat_item_eye_of_ender,
	mat_item_fire_charge,
	mat_item_firework_rocket,
	mat_item_fishing_rod,
	mat_item_flint_and_steel,
	mat_item_glow_berries,
	mat_item_glow_item_frame,
	mat_item_item_frame,
	mat_item_jungle_boat,
	mat_item_kelp,
	mat_item_lava_bucket,
	mat_item_lead,
	mat_item_lingering_potion,
	mat_item_melon_seeds,
	mat_item_minecart,
	mat_item_minecart_with_chest,
	mat_item_minecart_with_command_block,
	mat_item_minecart_with_furnace‌,
	mat_item_minecart_with_hopper,
	mat_item_minecart_with_tnt,
	mat_item_oak_boat,
	mat_item_painting,
	mat_item_potato,
	mat_item_powder_snow_bucket,
	mat_item_pumpkin_seeds,
	mat_item_redstone_dust,
	mat_item_snowball,
	mat_item_splash_potion,
	mat_item_spruce_boat,
	mat_item_string,
	mat_item_sweet_berries,
	mat_item_trident,
	mat_item_water_bucket,
	mat_item_wheat_seeds,
	mat_item_apple,
	mat_item_arrow,
	mat_item_baked_potato,
	mat_item_beetroot,
	mat_item_beetroot_soup,
	mat_item_black_dye,
	mat_item_blue_dye,
	mat_item_bone,
	mat_item_bone_meal,
	mat_item_book_and_quill,
	mat_item_bowl,
	mat_item_bread,
	mat_item_brown_dye,
	mat_item_bundle,
	mat_item_carrot_on_a_stick,
	mat_item_chainmail_boots,
	mat_item_chainmail_chestplate,
	mat_item_chainmail_helmet,
	mat_item_chainmail_leggings,
	mat_item_chorus_fruit,
	mat_item_compass,
	mat_item_cooked_chicken,
	mat_item_cooked_cod,
	mat_item_cooked_mutton,
	mat_item_cooked_porkchop,
	mat_item_cooked_rabbit,
	mat_item_cooked_salmon,
	mat_item_cookie,
	mat_item_cyan_dye,
	mat_item_debug_stick‌,
	mat_item_diamond_axe,
	mat_item_diamond_boots,
	mat_item_diamond_chestplate,
	mat_item_diamond_helmet,
	mat_item_diamond_hoe,
	mat_item_diamond_horse_armor,
	mat_item_diamond_leggings,
	mat_item_diamond_pickaxe,
	mat_item_diamond_shovel,
	mat_item_diamond_sword,
	mat_item_dried_kelp,
	mat_item_elytra,
	mat_item_empty_map,
	mat_item_enchanted_golden_apple,
	mat_item_goat_horn‌,
	mat_item_glass_bottle,
	mat_item_glow_ink_sac,
	mat_item_gold_ingot,
	mat_item_golden_apple,
	mat_item_golden_axe,
	mat_item_golden_boots,
	mat_item_golden_carrot,
	mat_item_golden_chestplate,
	mat_item_golden_helmet,
	mat_item_golden_hoe,
	mat_item_golden_horse_armor,
	mat_item_golden_leggings,
	mat_item_golden_pickaxe,
	mat_item_golden_shovel,
	mat_item_golden_sword,
	mat_item_gray_dye,
	mat_item_green_dye,
	mat_item_honeycomb,
	mat_item_honey_bottle,
	mat_item_ink_sac,
	mat_item_iron_axe,
	mat_item_iron_boots,
	mat_item_iron_chestplate,
	mat_item_iron_helmet,
	mat_item_iron_hoe,
	mat_item_iron_horse_armor,
	mat_item_iron_ingot,
	mat_item_iron_leggings,
	mat_item_iron_pickaxe,
	mat_item_iron_shovel,
	mat_item_iron_sword,
	mat_item_knowledge_book‌,
	mat_item_leather_boots,
	mat_item_leather_cap,
	mat_item_leather_horse_armor,
	mat_item_leather_pants,
	mat_item_leather_tunic,
	mat_item_light_blue_dye,
	mat_item_light_gray_dye,
	mat_item_lime_dye,
	mat_item_magenta_dye,
	mat_item_map_or_explorer_map,
	mat_item_melon_slice,
	mat_item_milk_bucket,
	mat_item_mushroom_stew,
	mat_item_music_disc_11,
	mat_item_music_disc_13,
	mat_item_music_disc_blocks,
	mat_item_music_disc_cat,
	mat_item_music_disc_chirp,
	mat_item_music_disc_far,
	mat_item_music_disc_mall,
	mat_item_music_disc_mellohi,
	mat_item_music_disc_pigstep,
	mat_item_music_disc_stal,
	mat_item_music_disc_strad,
	mat_item_music_disc_wait,
	mat_item_music_disc_ward,
	mat_item_name_tag,
	mat_item_netherite_axe,
	mat_item_netherite_boots,
	mat_item_netherite_chestplate,
	mat_item_netherite_helmet,
	mat_item_netherite_hoe,
	mat_item_netherite_leggings,
	mat_item_netherite_pickaxe,
	mat_item_netherite_shovel,
	mat_item_netherite_sword,
	mat_item_orange_dye,
	mat_item_pink_dye,
	mat_item_poisonous_potato,
	mat_item_potions,
	mat_item_pufferfish,
	mat_item_pumpkin_pie,
	mat_item_purple_dye,
	mat_item_rabbit_stew,
	mat_item_raw_beef,
	mat_item_raw_chicken,
	mat_item_raw_cod,
	mat_item_raw_mutton,
	mat_item_raw_porkchop,
	mat_item_raw_rabbit,
	mat_item_raw_salmon,
	mat_item_red_dye,
	mat_item_rotten_flesh,
	mat_item_saddle,
	mat_item_shears,
	mat_item_shield,
	mat_item_spectral_arrow‌,
	mat_item_spider_eye,
	mat_item_spyglass,
	mat_item_steak,
	mat_item_stone_axe,
	mat_item_stone_hoe,
	mat_item_stone_pickaxe,
	mat_item_stone_shovel,
	mat_item_stone_sword,
	mat_item_sugar,
	mat_item_suspicious_stew,
	mat_item_tipped_arrow,
	mat_item_totem_of_undying,
	mat_item_tropical_fish,
	mat_item_turtle_shell,
	mat_item_warped_fungus_on_a_stick,
	mat_item_wheat,
	mat_item_white_dye,
	mat_item_wooden_axe,
	mat_item_wooden_hoe,
	mat_item_wooden_pickaxe,
	mat_item_wooden_shovel,
	mat_item_wooden_sword,
	mat_item_written_book,
	mat_item_yellow_dye,
	mat_item_amethyst_shard,
	mat_item_banner_pattern_creeper_charge,
	mat_item_banner_pattern_flower_charge,
	mat_item_banner_pattern_globe,
	mat_item_banner_pattern_skull_charge,
	mat_item_banner_pattern_snout,
	mat_item_banner_pattern_thing,
	mat_item_blaze_powder,
	mat_item_blaze_rod,
	mat_item_book,
	mat_item_brick,
	mat_item_charcoal,
	mat_item_clay_ball,
	mat_item_clock,
	mat_item_coal,
	mat_item_copper_ingot,
	mat_item_diamond,
	mat_item_dragon_breath,
	mat_item_emerald,
	mat_item_enchanted_book,
	mat_item_feather,
	mat_item_fermented_spider_eye,
	mat_item_firework_star,
	mat_item_flint,
	mat_item_ghast_tear,
	mat_item_glistering_melon_slice,
	mat_item_glowstone_dust,
	mat_item_gold_nugget,
	mat_item_gunpowder,
	mat_item_heart_of_the_sea,
	mat_item_iron_nugget,
	mat_item_lapis_lazuli,
	mat_item_leather,
	mat_item_magma_cream,
	mat_item_nautilus_shell,
	mat_item_nether_brick,
	mat_item_nether_quartz,
	mat_item_nether_star,
	mat_item_netherite_ingot,
	mat_item_netherite_scrap,
	mat_item_paper,
	mat_item_phantom_membrane,
	mat_item_popped_chorus_fruit,
	mat_item_prismarine_crystals,
	mat_item_prismarine_shard,
	mat_item_rabbit_hide,
	mat_item_rabbit_foot,
	mat_item_raw_copper,
	mat_item_raw_gold,
	mat_item_raw_iron,
	mat_item_scute,
	mat_item_shulker_shell,
	mat_item_slimeball,
	mat_item_stick,
	mat_item_spawn_eggs,
	mat_item_axolotl_spawn_egg,
	mat_item_bat_spawn_egg,
	mat_item_bee_spawn_egg,
	mat_item_blaze_spawn_egg,
	mat_item_cat_spawn_egg,
	mat_item_cave_spider_spawn_egg,
	mat_item_chicken_spawn_egg,
	mat_item_cod_spawn_egg,
	mat_item_cow_spawn_egg,
	mat_item_creeper_spawn_egg,
	mat_item_dolphin_spawn_egg,
	mat_item_donkey_spawn_egg,
	mat_item_drowned_spawn_egg,
	mat_item_elder_guardian_spawn_egg,
	mat_item_enderman_spawn_egg,
	mat_item_endermite_spawn_egg,
	mat_item_evoker_spawn_egg,
	mat_item_fox_spawn_egg,
	mat_item_ghast_spawn_egg,
	mat_item_glow_squid_spawn_egg,
	mat_item_goat_spawn_egg,
	mat_item_guardian_spawn_egg,
	mat_item_hoglin_spawn_egg,
	mat_item_horse_spawn_egg,
	mat_item_husk_spawn_egg,
	mat_item_llama_spawn_egg,
	mat_item_magma_cube_spawn_egg,
	mat_item_mooshroom_spawn_egg,
	mat_item_mule_spawn_egg,
	mat_item_ocelot_spawn_egg,
	mat_item_panda_spawn_egg,
	mat_item_parrot_spawn_egg,
	mat_item_phantom_spawn_egg,
	mat_item_pig_spawn_egg,
	mat_item_piglin_spawn_egg,
	mat_item_piglin_brute_spawn_egg,
	mat_item_pillager_spawn_egg,
	mat_item_polar_bear_spawn_egg,
	mat_item_pufferfish_spawn_egg,
	mat_item_rabbit_spawn_egg,
	mat_item_ravager_spawn_egg,
	mat_item_salmon_spawn_egg,
	mat_item_sheep_spawn_egg,
	mat_item_shulker_spawn_egg,
	mat_item_silverfish_spawn_egg,
	mat_item_skeleton_horse_spawn_egg,
	mat_item_skeleton_spawn_egg,
	mat_item_slime_spawn_egg,
	mat_item_spider_spawn_egg,
	mat_item_squid_spawn_egg,
	mat_item_stray_spawn_egg,
	mat_item_strider_spawn_egg,
	mat_item_trader_llama_spawn_egg,
	mat_item_tropical_fish_spawn_egg,
	mat_item_turtle_spawn_egg,
	mat_item_vex_spawn_egg,
	mat_item_villager_spawn_egg,
	mat_item_vindicator_spawn_egg,
	mat_item_wandering_trader_spawn_egg,
	mat_item_witch_spawn_egg,
	mat_item_wither_skeleton_spawn_egg,
	mat_item_wolf_spawn_egg,
	mat_item_zoglin_spawn_egg,
	mat_item_zombie_horse_spawn_egg,
	mat_item_zombie_spawn_egg,
	mat_item_zombie_villager_spawn_egg,
	mat_item_zombified_piglin_spawn_egg,
	mat_item_acacia_button,
	mat_item_acacia_door,
	mat_item_acacia_fence,
	mat_item_acacia_fence_gate,
	mat_item_acacia_leaves,
	mat_item_acacia_log,
	mat_item_acacia_planks,
	mat_item_acacia_pressure_plate,
	mat_item_acacia_sapling,
	mat_item_acacia_sign,
	mat_item_acacia_slab,
	mat_item_acacia_stairs,
	mat_item_acacia_trapdoor,
	mat_item_acacia_wood,
	mat_item_activator_rail,
	mat_item_allium,
	mat_item_amethyst_cluster,
	mat_item_ancient_debris,
	mat_item_andesite,
	mat_item_andesite_slab,
	mat_item_andesite_stairs,
	mat_item_andesite_wall,
	mat_item_anvil,
	mat_item_azalea,
	mat_item_azalea_leaves,
	mat_item_azure_bluet,
	mat_item_bamboo,
	mat_item_bamboo_shoot,
	mat_item_beetroots,
	mat_item_barrel,
	mat_item_barrier,
	mat_item_basalt,
	mat_item_beacon,
	mat_item_bedrock,
	mat_item_beehive,
	mat_item_bee_nest,
	mat_item_bell,
	mat_item_big_dripleaf,
	mat_item_birch_button,
	mat_item_birch_door,
	mat_item_birch_fence,
	mat_item_birch_fence_gate,
	mat_item_birch_leaves,
	mat_item_birch_log,
	mat_item_birch_planks,
	mat_item_birch_pressure_plate,
	mat_item_birch_sapling,
	mat_item_birch_sign,
	mat_item_birch_slab,
	mat_item_birch_stairs,
	mat_item_birch_trapdoor,
	mat_item_birch_wood,
	mat_item_black_banner,
	mat_item_black_bed,
	mat_item_black_candle,
	mat_item_black_carpet,
	mat_item_black_concrete,
	mat_item_black_concrete_powder,
	mat_item_black_glazed_terracotta,
	mat_item_black_shulker_box,
	mat_item_black_stained_glass,
	mat_item_black_stained_glass_pane,
	mat_item_black_terracotta,
	mat_item_black_wool,
	mat_item_blackstone,
	mat_item_blackstone_slab,
	mat_item_blackstone_stairs,
	mat_item_blackstone_wall,
	mat_item_blast_furnace,
	mat_item_block_of_amethyst,
	mat_item_block_of_coal,
	mat_item_block_of_copper,
	mat_item_block_of_diamond,
	mat_item_block_of_emerald,
	mat_item_block_of_gold,
	mat_item_block_of_iron,
	mat_item_block_of_lapis_lazuli,
	mat_item_block_of_netherite,
	mat_item_block_of_quartz,
	mat_item_block_of_raw_copper,
	mat_item_block_of_raw_gold,
	mat_item_block_of_raw_iron,
	mat_item_block_of_redstone,
	mat_item_blue_banner,
	mat_item_blue_bed,
	mat_item_blue_candle,
	mat_item_blue_carpet,
	mat_item_blue_concrete,
	mat_item_blue_concrete_powder,
	mat_item_blue_glazed_terracotta,
	mat_item_blue_ice,
	mat_item_blue_orchid,
	mat_item_blue_shulker_box,
	mat_item_blue_stained_glass,
	mat_item_blue_stained_glass_pane,
	mat_item_blue_terracotta,
	mat_item_blue_wool,
	mat_item_bone_block,
	mat_item_bookshelf,
	mat_item_brain_coral,
	mat_item_brain_coral_block,
	mat_item_brain_coral_fan,
	mat_item_brewing_stand,
	mat_item_brick_slab,
	mat_item_brick_stairs,
	mat_item_brick_wall,
	mat_item_bricks,
	mat_item_brown_banner,
	mat_item_brown_bed,
	mat_item_brown_candle,
	mat_item_brown_carpet,
	mat_item_brown_concrete,
	mat_item_brown_concrete_powder,
	mat_item_brown_glazed_terracotta,
	mat_item_brown_mushroom,
	mat_item_brown_mushroom_block,
	mat_item_brown_shulker_box,
	mat_item_brown_stained_glass,
	mat_item_brown_stained_glass_pane,
	mat_item_brown_terracotta,
	mat_item_brown_wool,
	mat_item_bubble_coral,
	mat_item_bubble_coral_block,
	mat_item_bubble_coral_fan,
	mat_item_budding_amethyst,
	mat_item_cactus,
	mat_item_cake,
	mat_item_calcite,
	mat_item_campfire,
	mat_item_candle,
	mat_item_carrots,
	mat_item_cartography_table,
	mat_item_carved_pumpkin,
	mat_item_cauldron,
	mat_item_cave_vines,
	mat_item_chain,
	mat_item_chain_command_block,
	mat_item_chest,
	mat_item_chipped_anvil,
	mat_item_chiseled_deepslate,
	mat_item_chiseled_nether_bricks,
	mat_item_chiseled_polished_blackstone,
	mat_item_chiseled_quartz_block,
	mat_item_chiseled_red_sandstone,
	mat_item_chiseled_sandstone,
	mat_item_chiseled_stone_bricks,
	mat_item_chorus_flower,
	mat_item_chorus_plant,
	mat_item_clay,
	mat_item_coal_ore,
	mat_item_coarse_dirt,
	mat_item_cobbled_deepslate,
	mat_item_cobbled_deepslate_slab,
	mat_item_cobbled_deepslate_stairs,
	mat_item_cobbled_deepslate_wall,
	mat_item_cobblestone,
	mat_item_cobblestone_slab,
	mat_item_cobblestone_stairs,
	mat_item_cobblestone_wall,
	mat_item_cobweb,
	mat_item_cocoa,
	mat_item_command_block,
	mat_item_composter,
	mat_item_conduit,
	mat_item_copper_ore,
	mat_item_cornflower,
	mat_item_cracked_deepslate_bricks,
	mat_item_cracked_deepslate_tiles,
	mat_item_cracked_nether_bricks,
	mat_item_cracked_polished_blackstone_bricks,
	mat_item_cracked_stone_bricks,
	mat_item_crafting_table,
	mat_item_creeper_head,
	mat_item_crimson_button,
	mat_item_crimson_door,
	mat_item_crimson_fence,
	mat_item_crimson_fence_gate,
	mat_item_crimson_fungus,
	mat_item_crimson_hyphae,
	mat_item_crimson_nylium,
	mat_item_crimson_planks,
	mat_item_crimson_pressure_plate,
	mat_item_crimson_roots,
	mat_item_crimson_sign,
	mat_item_crimson_slab,
	mat_item_crimson_stairs,
	mat_item_crimson_stem,
	mat_item_crimson_trapdoor,
	mat_item_crying_obsidian,
	mat_item_cut_copper,
	mat_item_cut_copper_slab,
	mat_item_cut_copper_stairs,
	mat_item_cut_red_sandstone,
	mat_item_cut_red_sandstone_slab,
	mat_item_cut_sandstone,
	mat_item_cut_sandstone_slab,
	mat_item_cyan_banner,
	mat_item_cyan_bed,
	mat_item_cyan_candle,
	mat_item_cyan_carpet,
	mat_item_cyan_concrete,
	mat_item_cyan_concrete_powder,
	mat_item_cyan_glazed_terracotta,
	mat_item_cyan_shulker_box,
	mat_item_cyan_stained_glass,
	mat_item_cyan_stained_glass_pane,
	mat_item_cyan_terracotta,
	mat_item_cyan_wool,
	mat_item_damaged_anvil,
	mat_item_dandelion,
	mat_item_dark_oak_button,
	mat_item_dark_oak_door,
	mat_item_dark_oak_fence,
	mat_item_dark_oak_fence_gate,
	mat_item_dark_oak_leaves,
	mat_item_dark_oak_log,
	mat_item_dark_oak_planks,
	mat_item_dark_oak_pressure_plate,
	mat_item_dark_oak_sapling,
	mat_item_dark_oak_sign,
	mat_item_dark_oak_slab,
	mat_item_dark_oak_stairs,
	mat_item_dark_oak_trapdoor,
	mat_item_dark_oak_wood,
	mat_item_dark_prismarine,
	mat_item_dark_prismarine_slab,
	mat_item_dark_prismarine_stairs,
	mat_item_daylight_detector,
	mat_item_dead_brain_coral,
	mat_item_dead_brain_coral_block,
	mat_item_dead_brain_coral_fan,
	mat_item_dead_bubble_coral,
	mat_item_dead_bubble_coral_block,
	mat_item_dead_bubble_coral_fan,
	mat_item_dead_bush,
	mat_item_dead_fire_coral,
	mat_item_dead_fire_coral_block,
	mat_item_dead_fire_coral_fan,
	mat_item_dead_horn_coral,
	mat_item_dead_horn_coral_block,
	mat_item_dead_horn_coral_fan,
	mat_item_dead_tube_coral,
	mat_item_dead_tube_coral_block,
	mat_item_dead_tube_coral_fan,
	mat_item_deepslate,
	mat_item_deepslate_bricks,
	mat_item_deepslate_brick_slab,
	mat_item_deepslate_brick_stairs,
	mat_item_deepslate_brick_wall,
	mat_item_deepslate_coal_ore,
	mat_item_deepslate_copper_ore,
	mat_item_deepslate_diamond_ore,
	mat_item_deepslate_emerald_ore,
	mat_item_deepslate_gold_ore,
	mat_item_deepslate_iron_ore,
	mat_item_deepslate_lapis_lazuli_ore,
	mat_item_deepslate_redstone_ore,
	mat_item_deepslate_tiles,
	mat_item_deepslate_tile_slab,
	mat_item_deepslate_tile_stairs,
	mat_item_deepslate_tile_wall,
	mat_item_detector_rail,
	mat_item_diamond_ore,
	mat_item_diorite,
	mat_item_diorite_slab,
	mat_item_diorite_stairs,
	mat_item_diorite_wall,
	mat_item_dirt,
	mat_item_dirt_path,
	mat_item_dispenser,
	mat_item_dragon_egg,
	mat_item_dragon_head,
	mat_item_dried_kelp_block,
	mat_item_dripstone_block,
	mat_item_dropper,
	mat_item_emerald_ore,
	mat_item_enchanting_table,
	mat_item_end_portal_frame,
	mat_item_end_rod,
	mat_item_end_stone,
	mat_item_end_stone_brick_slab,
	mat_item_end_stone_brick_stairs,
	mat_item_end_stone_brick_wall,
	mat_item_end_stone_bricks,
	mat_item_ender_chest,
	mat_item_exposed_copper,
	mat_item_exposed_cut_copper,
	mat_item_exposed_cut_copper_slab,
	mat_item_exposed_cut_copper_stairs,
	mat_item_farmland,
	mat_item_fern,
	mat_item_fire,
	mat_item_fire_coral,
	mat_item_fire_coral_block,
	mat_item_fire_coral_fan,
	mat_item_fletching_table,
	mat_item_flower_pot,
	mat_item_flowering_azalea,
	mat_item_flowering_azalea_leaves,
	mat_item_furnace,
	mat_item_gilded_blackstone,
	mat_item_glass,
	mat_item_glass_pane,
	mat_item_glow_lichen,
	mat_item_glowstone,
	mat_item_gold_ore,
	mat_item_granite,
	mat_item_granite_slab,
	mat_item_granite_stairs,
	mat_item_granite_wall,
	mat_item_grass,
	mat_item_grass_block,
	mat_item_gravel,
	mat_item_gray_banner,
	mat_item_gray_bed,
	mat_item_gray_candle,
	mat_item_gray_carpet,
	mat_item_gray_concrete,
	mat_item_gray_concrete_powder,
	mat_item_gray_glazed_terracotta,
	mat_item_gray_shulker_box,
	mat_item_gray_stained_glass,
	mat_item_gray_stained_glass_pane,
	mat_item_gray_terracotta,
	mat_item_gray_wool,
	mat_item_green_banner,
	mat_item_green_bed,
	mat_item_green_candle,
	mat_item_green_carpet,
	mat_item_green_concrete,
	mat_item_green_concrete_powder,
	mat_item_green_glazed_terracotta,
	mat_item_green_shulker_box,
	mat_item_green_stained_glass,
	mat_item_green_stained_glass_pane,
	mat_item_green_terracotta,
	mat_item_green_wool,
	mat_item_grindstone,
	mat_item_hanging_roots,
	mat_item_hay_bale,
	mat_item_heavy_weighted_pressure_plate,
	mat_item_honey_block,
	mat_item_honeycomb_block,
	mat_item_hopper,
	mat_item_horn_coral,
	mat_item_horn_coral_block,
	mat_item_horn_coral_fan,
	mat_item_ice,
	mat_item_infested_chiseled_stone_bricks,
	mat_item_infested_cobblestone,
	mat_item_infested_cracked_stone_bricks,
	mat_item_infested_deepslate,
	mat_item_infested_mossy_stone_bricks,
	mat_item_infested_stone,
	mat_item_infested_stone_bricks,
	mat_item_iron_bars,
	mat_item_iron_door,
	mat_item_iron_ore,
	mat_item_iron_trapdoor,
	mat_item_jack_o_lantern,
	mat_item_jigsaw_block,
	mat_item_jukebox,
	mat_item_jungle_button,
	mat_item_jungle_door,
	mat_item_jungle_fence,
	mat_item_jungle_fence_gate,
	mat_item_jungle_leaves,
	mat_item_jungle_log,
	mat_item_jungle_planks,
	mat_item_jungle_pressure_plate,
	mat_item_jungle_sapling,
	mat_item_jungle_sign,
	mat_item_jungle_slab,
	mat_item_jungle_stairs,
	mat_item_jungle_trapdoor,
	mat_item_jungle_wood,
	mat_item_ladder,
	mat_item_lantern,
	mat_item_lapis_lazuli_ore,
	mat_item_large_amethyst_bud,
	mat_item_large_fern,
	mat_item_lava,
	mat_item_lectern,
	mat_item_lever,
	mat_item_light_block,
	mat_item_light_blue_banner,
	mat_item_light_blue_bed,
	mat_item_light_blue_candle,
	mat_item_light_blue_carpet,
	mat_item_light_blue_concrete,
	mat_item_light_blue_concrete_powder,
	mat_item_light_blue_glazed_terracotta,
	mat_item_light_blue_shulker_box,
	mat_item_light_blue_stained_glass,
	mat_item_light_blue_stained_glass_pane,
	mat_item_light_blue_terracotta,
	mat_item_light_blue_wool,
	mat_item_light_gray_banner,
	mat_item_light_gray_bed,
	mat_item_light_gray_candle,
	mat_item_light_gray_carpet,
	mat_item_light_gray_concrete,
	mat_item_light_gray_concrete_powder,
	mat_item_light_gray_glazed_terracotta,
	mat_item_light_gray_shulker_box,
	mat_item_light_gray_stained_glass,
	mat_item_light_gray_stained_glass_pane,
	mat_item_light_gray_terracotta,
	mat_item_light_gray_wool,
	mat_item_light_weighted_pressure_plate,
	mat_item_lightning_rod,
	mat_item_lilac,
	mat_item_lily_of_the_valley,
	mat_item_lily_pad,
	mat_item_lime_banner,
	mat_item_lime_bed,
	mat_item_lime_candle,
	mat_item_lime_carpet,
	mat_item_lime_concrete,
	mat_item_lime_concrete_powder,
	mat_item_lime_glazed_terracotta,
	mat_item_lime_shulker_box,
	mat_item_lime_stained_glass,
	mat_item_lime_stained_glass_pane,
	mat_item_lime_terracotta,
	mat_item_lime_wool,
	mat_item_lodestone,
	mat_item_loom,
	mat_item_magenta_banner,
	mat_item_magenta_bed,
	mat_item_magenta_candle,
	mat_item_magenta_carpet,
	mat_item_magenta_concrete,
	mat_item_magenta_concrete_powder,
	mat_item_magenta_glazed_terracotta,
	mat_item_magenta_shulker_box,
	mat_item_magenta_stained_glass,
	mat_item_magenta_stained_glass_pane,
	mat_item_magenta_terracotta,
	mat_item_magenta_wool,
	mat_item_magma_block,
	mat_item_medium_amethyst_bud,
	mat_item_melon,
	mat_item_melon_stem,
	mat_item_moss_block,
	mat_item_moss_carpet,
	mat_item_mossy_cobblestone,
	mat_item_mossy_cobblestone_slab,
	mat_item_mossy_cobblestone_stairs,
	mat_item_mossy_cobblestone_wall,
	mat_item_mossy_stone_brick_slab,
	mat_item_mossy_stone_brick_stairs,
	mat_item_mossy_stone_brick_wall,
	mat_item_mossy_stone_bricks,
	mat_item_mushroom_stem,
	mat_item_mycelium,
	mat_item_nether_brick_fence,
	mat_item_nether_brick_slab,
	mat_item_nether_brick_stairs,
	mat_item_nether_brick_wall,
	mat_item_nether_bricks,
	mat_item_nether_gold_ore,
	mat_item_nether_quartz_ore,
	mat_item_nether_sprouts,
	mat_item_nether_wart,
	mat_item_nether_wart_block,
	mat_item_netherrack,
	mat_item_note_block,
	mat_item_oak_button,
	mat_item_oak_door,
	mat_item_oak_fence,
	mat_item_oak_fence_gate,
	mat_item_oak_leaves,
	mat_item_oak_log,
	mat_item_oak_planks,
	mat_item_oak_pressure_plate,
	mat_item_oak_sapling,
	mat_item_oak_sign,
	mat_item_oak_slab,
	mat_item_oak_stairs,
	mat_item_oak_trapdoor,
	mat_item_oak_wood,
	mat_item_observer,
	mat_item_obsidian,
	mat_item_ominous_banner,
	mat_item_orange_banner,
	mat_item_orange_bed,
	mat_item_orange_candle,
	mat_item_orange_carpet,
	mat_item_orange_concrete,
	mat_item_orange_concrete_powder,
	mat_item_orange_glazed_terracotta,
	mat_item_orange_shulker_box,
	mat_item_orange_stained_glass,
	mat_item_orange_stained_glass_pane,
	mat_item_orange_terracotta,
	mat_item_orange_tulip,
	mat_item_orange_wool,
	mat_item_oxeye_daisy,
	mat_item_oxidized_copper,
	mat_item_oxidized_cut_copper,
	mat_item_oxidized_cut_copper_slab,
	mat_item_oxidized_cut_copper_stairs,
	mat_item_packed_ice,
	mat_item_peony,
	mat_item_petrified_oak_slab,
	mat_item_pink_banner,
	mat_item_pink_bed,
	mat_item_pink_candle,
	mat_item_pink_carpet,
	mat_item_pink_concrete,
	mat_item_pink_concrete_powder,
	mat_item_pink_glazed_terracotta,
	mat_item_pink_shulker_box,
	mat_item_pink_stained_glass,
	mat_item_pink_stained_glass_pane,
	mat_item_pink_terracotta,
	mat_item_pink_tulip,
	mat_item_pink_wool,
	mat_item_piston,
	mat_item_player_head,
	mat_item_podzol,
	mat_item_pointed_dripstone,
	mat_item_polished_andesite,
	mat_item_polished_andesite_slab,
	mat_item_polished_andesite_stairs,
	mat_item_polished_basalt,
	mat_item_polished_blackstone,
	mat_item_polished_blackstone_brick_slab,
	mat_item_polished_blackstone_brick_stairs,
	mat_item_polished_blackstone_brick_wall,
	mat_item_polished_blackstone_bricks,
	mat_item_polished_blackstone_button,
	mat_item_polished_blackstone_pressure_plate,
	mat_item_polished_blackstone_slab,
	mat_item_polished_blackstone_stairs,
	mat_item_polished_blackstone_wall,
	mat_item_polished_diorite,
	mat_item_polished_diorite_slab,
	mat_item_polished_diorite_stairs,
	mat_item_polished_granite,
	mat_item_polished_granite_slab,
	mat_item_polished_granite_stairs,
	mat_item_polished_deepslate,
	mat_item_polished_deepslate_slab,
	mat_item_polished_deepslate_stairs,
	mat_item_polished_deepslate_wall,
	mat_item_poppy,
	mat_item_potatoes,
	mat_item_powder_snow,
	mat_item_powered_rail,
	mat_item_prismarine,
	mat_item_prismarine_brick_slab,
	mat_item_prismarine_brick_stairs,
	mat_item_prismarine_bricks,
	mat_item_prismarine_slab,
	mat_item_prismarine_stairs,
	mat_item_prismarine_wall,
	mat_item_pumpkin,
	mat_item_pumpkin_stem,
	mat_item_purple_banner,
	mat_item_purple_bed,
	mat_item_purple_candle,
	mat_item_purple_carpet,
	mat_item_purple_concrete,
	mat_item_purple_concrete_powder,
	mat_item_purple_glazed_terracotta,
	mat_item_purple_shulker_box,
	mat_item_purple_stained_glass,
	mat_item_purple_stained_glass_pane,
	mat_item_purple_terracotta,
	mat_item_purple_wool,
	mat_item_purpur_block,
	mat_item_purpur_pillar,
	mat_item_purpur_slab,
	mat_item_purpur_stairs,
	mat_item_quartz_bricks,
	mat_item_quartz_pillar,
	mat_item_quartz_slab,
	mat_item_quartz_stairs,
	mat_item_rail,
	mat_item_red_banner,
	mat_item_red_bed,
	mat_item_red_candle,
	mat_item_red_carpet,
	mat_item_red_concrete,
	mat_item_red_concrete_powder,
	mat_item_red_glazed_terracotta,
	mat_item_red_mushroom,
	mat_item_red_mushroom_block,
	mat_item_red_nether_brick_slab,
	mat_item_red_nether_brick_stairs,
	mat_item_red_nether_brick_wall,
	mat_item_red_nether_bricks,
	mat_item_red_sand,
	mat_item_red_sandstone,
	mat_item_red_sandstone_slab,
	mat_item_red_sandstone_stairs,
	mat_item_red_sandstone_wall,
	mat_item_red_shulker_box,
	mat_item_red_stained_glass,
	mat_item_red_stained_glass_pane,
	mat_item_red_terracotta,
	mat_item_red_tulip,
	mat_item_red_wool,
	mat_item_redstone_comparator,
	mat_item_redstone_lamp,
	mat_item_redstone_ore,
	mat_item_redstone_repeater,
	mat_item_redstone_torch,
	mat_item_redstone_wire,
	mat_item_repeating_command_block,
	mat_item_respawn_anchor,
	mat_item_rooted_dirt,
	mat_item_rose_bush,
	mat_item_sand,
	mat_item_sandstone,
	mat_item_sandstone_slab,
	mat_item_sandstone_stairs,
	mat_item_sandstone_wall,
	mat_item_scaffolding,
	mat_item_sculk_sensor,
	mat_item_sea_lantern,
	mat_item_sea_pickle,
	mat_item_seagrass,
	mat_item_shroomlight,
	mat_item_shulker_box,
	mat_item_skeleton_skull,
	mat_item_slime_block,
	mat_item_small_amethyst_bud,
	mat_item_small_dripleaf,
	mat_item_smithing_table,
	mat_item_smoker,
	mat_item_smooth_basalt,
	mat_item_smooth_quartz_block,
	mat_item_smooth_quartz_slab,
	mat_item_smooth_quartz_stairs,
	mat_item_smooth_red_sandstone,
	mat_item_smooth_red_sandstone_slab,
	mat_item_smooth_red_sandstone_stairs,
	mat_item_smooth_sandstone,
	mat_item_smooth_sandstone_slab,
	mat_item_smooth_sandstone_stairs,
	mat_item_smooth_stone,
	mat_item_smooth_stone_slab,
	mat_item_snow,
	mat_item_snow_block,
	mat_item_soul_campfire,
	mat_item_soul_fire,
	mat_item_soul_lantern,
	mat_item_soul_sand,
	mat_item_soul_soil,
	mat_item_soul_torch,
	mat_item_spawner,
	mat_item_sponge,
	mat_item_spore_blossom,
	mat_item_spruce_button,
	mat_item_spruce_door,
	mat_item_spruce_fence,
	mat_item_spruce_fence_gate,
	mat_item_spruce_leaves,
	mat_item_spruce_log,
	mat_item_spruce_planks,
	mat_item_spruce_pressure_plate,
	mat_item_spruce_sapling,
	mat_item_spruce_sign,
	mat_item_spruce_slab,
	mat_item_spruce_stairs,
	mat_item_spruce_trapdoor,
	mat_item_spruce_wood,
	mat_item_sticky_piston,
	mat_item_stone,
	mat_item_stone_brick_slab,
	mat_item_stone_brick_stairs,
	mat_item_stone_brick_wall,
	mat_item_stone_bricks,
	mat_item_stone_button,
	mat_item_stone_pressure_plate,
	mat_item_stone_slab,
	mat_item_stone_stairs,
	mat_item_stonecutter,
	mat_item_stripped_acacia_log,
	mat_item_stripped_acacia_wood,
	mat_item_stripped_birch_log,
	mat_item_stripped_birch_wood,
	mat_item_stripped_crimson_hyphae,
	mat_item_stripped_crimson_stem,
	mat_item_stripped_dark_oak_log,
	mat_item_stripped_dark_oak_wood,
	mat_item_stripped_jungle_log,
	mat_item_stripped_jungle_wood,
	mat_item_stripped_oak_log,
	mat_item_stripped_oak_wood,
	mat_item_stripped_spruce_log,
	mat_item_stripped_spruce_wood,
	mat_item_stripped_warped_hyphae,
	mat_item_stripped_warped_stem,
	mat_item_structure_block,
	mat_item_structure_void,
	mat_item_sugar_cane,
	mat_item_sunflower,
	mat_item_sweet_berry_bush,
	mat_item_tall_grass,
	mat_item_tall_seagrass,
	mat_item_target,
	mat_item_terracotta,
	mat_item_tinted_glass,
	mat_item_tnt,
	mat_item_torch,
	mat_item_trapped_chest,
	mat_item_tripwire,
	mat_item_tripwire_hook,
	mat_item_tube_coral,
	mat_item_tube_coral_block,
	mat_item_tube_coral_fan,
	mat_item_tuff,
	mat_item_turtle_egg,
	mat_item_twisting_vines,
	mat_item_vines,
	mat_item_warped_button,
	mat_item_warped_door,
	mat_item_warped_fence,
	mat_item_warped_fence_gate,
	mat_item_warped_fungus,
	mat_item_warped_hyphae,
	mat_item_warped_nylium,
	mat_item_warped_planks,
	mat_item_warped_pressure_plate,
	mat_item_warped_roots,
	mat_item_warped_sign,
	mat_item_warped_slab,
	mat_item_warped_stairs,
	mat_item_warped_stem,
	mat_item_warped_trapdoor,
	mat_item_warped_wart_block,
	mat_item_water,
	mat_item_waxed_block_of_copper,
	mat_item_waxed_cut_copper,
	mat_item_waxed_cut_copper_slab,
	mat_item_waxed_cut_copper_stairs,
	mat_item_waxed_exposed_copper,
	mat_item_waxed_exposed_cut_copper,
	mat_item_waxed_exposed_cut_copper_slab,
	mat_item_waxed_exposed_cut_copper_stairs,
	mat_item_waxed_oxidized_copper,
	mat_item_waxed_oxidized_cut_copper,
	mat_item_waxed_oxidized_cut_copper_slab,
	mat_item_waxed_oxidized_cut_copper_stairs,
	mat_item_waxed_weathered_copper,
	mat_item_waxed_weathered_cut_copper,
	mat_item_waxed_weathered_cut_copper_slab,
	mat_item_waxed_weathered_cut_copper_stairs,
	mat_item_weathered_copper,
	mat_item_weathered_cut_copper,
	mat_item_weathered_cut_copper_slab,
	mat_item_weathered_cut_copper_stairs,
	mat_item_weeping_vines,
	mat_item_wet_sponge,
	mat_item_wheat_crops,
	mat_item_white_banner,
	mat_item_white_bed,
	mat_item_white_candle,
	mat_item_white_carpet,
	mat_item_white_concrete,
	mat_item_white_concrete_powder,
	mat_item_white_glazed_terracotta,
	mat_item_white_shulker_box,
	mat_item_white_stained_glass,
	mat_item_white_stained_glass_pane,
	mat_item_white_terracotta,
	mat_item_white_tulip,
	mat_item_white_wool,
	mat_item_wither_rose,
	mat_item_wither_skeleton_skull,
	mat_item_yellow_banner,
	mat_item_yellow_bed,
	mat_item_yellow_candle,
	mat_item_yellow_carpet,
	mat_item_yellow_concrete,
	mat_item_yellow_concrete_powder,
	mat_item_yellow_glazed_terracotta,
	mat_item_yellow_shulker_box,
	mat_item_yellow_stained_glass,
	mat_item_yellow_stained_glass_pane,
	mat_item_yellow_terracotta,
	mat_item_yellow_wool,
	mat_item_zombie_head

} mat_item_id_t;

typedef enum {

	mat_item_tag_equipment, // equipment tag
		mat_item_tag_weapon, // weapon tag
			mat_item_tag_tier, // tier tag

		mat_item_tag_armor, // armor tag

	mat_item_tag_stacks,
		mat_item_tag_stacks_16,

	mat_item_tag_block, // block tag

	mat_item_tag_food, // food tag

	mat_item_tag_entity, // entity tag
		mat_item_tag_entity_place, // throw_speed tag

	mat_item_tag_max

} mat_item_tag_t;

typedef struct {

	utl_bitset(mat_item_tag_max - 1, tags_set);

	union {

		struct {

			mat_equipment_type_t type;
			uint32_t max_durability;

		} equipment;

		struct {
			
			float32_t attack_speed;
			float32_t damage;

		} weapon;

		mat_equipment_tier_t tier;

		struct {

			uint8_t defense;
			uint8_t toughness;
			uint8_t knockback_resistance;

		} armor;

		mat_block_id_t block;

		struct {

			float32_t saturation;

			uint8_t speed; // how fast you eat it
			uint8_t food; // how much hunger it restores

		} food;

		uint32_t entity;

		float32_t throw_speed;

	} tags[];

} mat_item_t;

extern const mat_item_t* mat_items[];
extern const mat_item_id_t mat_items_protocol[];

static inline const mat_item_t* mat_getItemById(mat_item_id_t id) {
	return mat_items[id];
}

static inline bool_t mat_isEquipment(const mat_item_t* item) {
	return utl_testBit(item->tags_set, mat_item_tag_equipment);
}

static inline mat_equipment_type_t mat_getEquipmentType(const mat_item_t* item) {
	return item->tags[0].equipment.type;
}

static inline uint32_t mat_getMaxDurability(const mat_item_t* item) {
	return item->tags[0].equipment.max_durability;
}

static inline bool_t mat_isWeapon(const mat_item_t* item) {
	return utl_testBit(item->tags_set, mat_item_tag_weapon);
}

static inline float32_t mat_getAttackSpeed(const mat_item_t* item) {
	return item->tags[1].weapon.attack_speed;
}

static inline float32_t mat_getDamage(const mat_item_t* item) {
	return item->tags[1].weapon.damage;
}

static inline bool_t mat_isTiered(const mat_item_t* item) {
	return utl_testBit(item->tags_set, mat_item_tag_tier);
}

static inline mat_equipment_tier_t mat_getTier(const mat_item_t* item) {
	return item->tags[2].tier;
}

static inline bool_t mat_isArmor(const mat_item_t* item) {
	return utl_testBit(item->tags_set, mat_item_tag_armor);
}

static inline uint8_t mat_getDefense(const mat_item_t* item) {
	return item->tags[1].armor.defense;
}

static inline uint8_t mat_getToughness(const mat_item_t* item) {
	return item->tags[1].armor.toughness;
}

static inline uint8_t mat_getKnockbackResistance(const mat_item_t* item) {
	return item->tags[1].armor.knockback_resistance;
}

static inline bool_t mat_itemStacks(const mat_item_t* item) {
	return utl_testBit(item->tags_set, mat_item_tag_stacks);
}

static inline bool_t mat_itemStacksTo16(const mat_item_t* item) {
	return utl_testBit(item->tags_set, mat_item_tag_stacks_16);
}

static inline bool_t mat_isBlock(const mat_item_t* item) {
	return utl_testBit(item->tags_set, mat_item_tag_block);
}

static inline mat_block_id_t mat_getBlockId(const mat_item_t* item) {
	return item->tags[0].block;
}

static inline bool_t mat_isFood(const mat_item_t* item) {
	return utl_testBit(item->tags_set, mat_item_tag_food);
}

static inline float32_t mat_getSaturation(const mat_item_t* item) {
	return item->tags[0].food.saturation;
}

static inline uint8_t mat_getFood(const mat_item_t* item) {
	return item->tags[0].food.food;
}

static inline uint8_t mat_getConsumeSpeed(const mat_item_t* item) {
	return item->tags[0].food.speed;
}

static inline bool_t mat_isEntity(const mat_item_t* item) {
	return utl_testBit(item->tags_set, mat_item_tag_entity);
}

static inline uint32_t mat_getEntity(const mat_item_t* item) {
	return item->tags[0].entity;
}

static inline bool_t mat_isPlacedEntity(const mat_item_t* item) {
	return utl_testBit(item->tags_set, mat_item_tag_entity_place);
}

static inline float32_t mat_getThrowSpeed(const mat_item_t* item) {
	return item->tags[0].throw_speed;
}